### ISSUE TITLE
some mistakes in Paddle installation wiki of docker version

### ISSUE THREAD

**Issue by fifar** [baidu/Paddle#10]
As mentioned in the [Chinese installation wiki](http://www.paddlepaddle.org/doc_cn/build_and_install/install/docker_install.html), there are 6 docker images, such as **paddledev/paddlepaddle:latest-cpu**. But from [docker images repository](https://hub.docker.com/r/paddledev/paddle/tags/), the useful ones are images like **paddledev/paddle:cpu-latest**.
So, command of Installing and Running docker image should be as follows,
```
$ docker run -it paddledev/paddle:cpu-latest
```
Thanks.

**Comment by emailweixu** [comment]
We are aware of this. The doc in github repo has already been fixed. The documentation site wll be update soon.,
