### ISSUE TITLE
cblas.cmake issue for mkl

### ISSUE THREAD

**Issue by apollos** [baidu/Paddle#103]
I suggest change the file to 

diff --git a/cmake/cblas.cmake b/cmake/cblas.cmake
index 617bd7e..c8fba96 100644
--- a/cmake/cblas.cmake
+++ b/cmake/cblas.cmake
@@ -17,10 +17,10 @@
 ## Find MKL First.
 set(MKL_ROOT $ENV{MKL_ROOT} CACHE PATH "Folder contains MKL")
 
-find_path(MKL_INCLUDE_DIR mkl.h PATHS ${MKL_ROOT}/include)
-find_library(MKL_CORE_LIB NAMES mkl_core PATHS ${MKL_ROOT}/lib)
-find_library(MKL_SEQUENTIAL_LIB NAMES mkl_sequential PATHS ${MKL_ROOT}/lib)
-find_library(MKL_INTEL_LP64 NAMES mkl_intel_lp64 PATHS ${MKL_ROOT}/lib)
+find_path(MKL_INCLUDE_DIR mkl.h PATHS ${MKL_ROOT}/include ${MKL_ROOT}/lib/intel64)
+find_library(MKL_CORE_LIB NAMES mkl_core PATHS ${MKL_ROOT}/lib ${MKL_ROOT}/lib/intel64)
+find_library(MKL_SEQUENTIAL_LIB NAMES mkl_sequential PATHS ${MKL_ROOT}/lib ${MKL_ROOT}/lib/intel64)
+find_library(MKL_INTEL_LP64 NAMES mkl_intel_lp64 PATHS ${MKL_ROOT}/lib ${MKL_ROOT}/lib/intel64)
 
 
 if(MKL_INCLUDE_DIR AND MKL_CORE_LIB AND MKL_SEQUENTIAL_LIB AND MKL_INTEL_LP64)

**Comment by reyoung** [comment]
Please send a pull request for this if you are convenient. Thank you.
If you don't want to fix it, we will patch it soon.

**Comment by backyes** [comment]
change to pull request: 
https://github.com/baidu/Paddle/pull/188.
