### ISSUE TITLE
image_classification cifar-10 train (use sparse trainning)

### ISSUE THREAD

**Issue by shenhuinuist** [baidu/Paddle#105]
When execute sparse training, we  need to set sparse_update=True  in network config. Where should I set the command when I train image_classification cifar-10?

**Comment by qingqing01** [comment]
@shenhuinuist  the `sparse_update` is an attribute of [ParamAttr](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/attrs.html).  For example

```python
 fc = fc_layer(input=data, size=128, param_attr=ParamAttr(sparse_update=True))
```
The sparse training is usually used to accelerate calculation when input is **sparse input data** with highly dimension. 

**But** the data for  image classification of cifar-10 is dense type, this `sparse_update` is not applicable to this case.

In addition, if you want to train a sparse weight, just need to

**Comment by shenhuinuist** [comment]
@qingqing01  Thank you so much . Now , I set  sparse_update =True and sparse_remote_update = False in paddle.trainer_config_helpers.attr.py , the input data was still image classification of cifar-10, the error was as follows: TypeError: __init__( ) got an un expected keyword argument ‘sparse_update’. I have two questions. Where does paddle execute the command ? What's more, How does paddle  judge the input data is sparse or not ?

**Comment by qingqing01** [comment]
@shenhuinuist  I have mentioned above, the cifar-10 data is not sparse input. So the `sparse_update` is not applicable to this case. The data type is defined in this [line](https://github.com/baidu/Paddle/blob/master/demo/image_classification/image_provider.py#L55)  of data provider file. The [data provider](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html) file defines the types of the input data and provides training or testing data to PaddlePaddle. 
In addition, the quick start tutorial is  an simple demo to guide user to use PaddlePaddle, see [Chinese document](http://www.paddlepaddle.org/doc_cn/demo/quick_start/index.html) or [English document](http://www.paddlepaddle.org/doc/demo/quick_start/index_en.html)

Thanks!

**Comment by shenhuinuist** [comment]
@qingqing01  Thank you!
