### ISSUE TITLE
How to reduce the memory consumption!

### ISSUE THREAD

**Issue by NIULQfromNJU** [baidu/Paddle#120]
At first I want to train LR on a large scale dataset using one single machine. In my perspective, paddle only need  to maintain parameters and some batch data instead of all training data, so one machine is enough.  But i find that Paddle's training process will produce some evaluation results such as cost, auc, etc. and  paddle's memory consumption is too large.
So i want to know how paddle manage the memory for training and evaluation module during the training process.
Besides, how to reduce paddle's memory consumption to minimum? Should i modify the source code to remove some large-memory-consumption module such as global evaluation?
Thx~

**Comment by backyes** [comment]
You can try to show more quantitive details about your experiments, such as the size of Model Parameters, Mini-batch Train Data, total train Data, total memory size exhausted by PaddlePaddle. 

The memory size allocated for training mainly comes from the cache/buffer memory in DataProvider, Model Parameters, Mini-batch Data, and some additional memory for some SGD optimiser. 

Different DataProvider could exhaust different memories for shuffling train data for better convergence. Different SGD optimiser could also exhaust different orders of magnitude memories. 

If your model owns high-dimensiones with input layers, the memories exhausted by parameters could account for BIG part of all memories. You can use sparse_update to reduce gradient memory at runtime.

In general, PaddlePaddle supports using sparse training for BIG model in local and cluster training to reduce memory  and computation needs and even gain better network efficiency for BIG model. PaddlePaddle even supports training the model whose size is larger the all CPU host memory size with distributed sparse training(using sparse_remote_parameter option).

Check guide as follow link:
http://www.paddlepaddle.org/doc/ui/cmd_argument/use_case.html?highlight=sparse
http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/attrs.html?highlight=sparse_update 

More details about sparse training can be reached later.

**Comment by NIULQfromNJU** [comment]
hi @backyes @reyoung @emailweixu 
I find that when using batch learning, paddle will load all training data and train some iterations (as we can see, paddle's memory cost increases when pass=0, later paddle's memory cost will not change when pass >0). This style will require a large memory cost. 
Actually, even using batch learning, paddle only need maintain current batch data instead of all training data. In this way, paddle uses mini-batch + streaming, may paddle use more time because of loading next training data, but less memory cost.
So whether paddle support training large scale data using streaming(online) style or not?
Thx~

**Comment by backyes** [comment]
PaddlePaddle INDEED supports training model with streaming style.  Please consult details in DataProvider. @reyoung can guide you for DataProvider.

Before you show more quantitive data, we can not help you to do further diagnosis.  

Here it's some understanding of the internals of linux virtual memory.
E.G,  at the beginning of starting do mini-batch training, PaddlePaddle could load all/part of train data to memory for shuffling. With the background of that linux will best effort to buffer disk train data in buffer cache, the memory  exhausted by "PaddlePaddle" could be just be originated  from Linux's buffer cache, which will be swapped to disk again automatically if physical memory is limit while do mini-batch training. And the overhead from this swapping could be so little for CPU computation-intensity mini-batch Train, because the disk swap is I/O intensive. The core factor that impact you performance  could be the ratio between the IO time and Training Mini-batch time for streaming style data provider.
Please discriminate the memory exhausted by PaddlePaddle internal data structure and by linux virtual memory mechanism.

**Comment by NIULQfromNJU** [comment]
Thanks~ @backyes @reyoung i will check the streaming way in dataprovider.

Actually i have a training data including 300 millions samples, and my PC (RAM=36GB) can not load all training data while paddle(LR+Adam) process will be killed. Hence i sub-sample 1/10 training data and paddle running will be ok with %MEM>60%. But this is not my wish.
I expect paddle can run in streaming way and reduce the memory cost, so there is no need for subsampling.

some training snippet:
 Batch=300 samples=3840000 AvgCost=0.0509063 CurrentCost=0.0509063 Eval:  CurrentEval: 
I0927 12:43:14.037856 22516 TrainerInternal.cpp:162]  Batch=600 samples=7680000 AvgCost=0.0312522 CurrentCost=0.0115982 Eval:  CurrentEval: 
I0927 12:44:20.110793 22516 TrainerInternal.cpp:162]  Batch=900 samples=11520000 AvgCost=0.0237599 CurrentCost=0.00877524 Eval:  CurrentEval: 
I0927 12:45:12.129215 22516 Tester.cpp:111]  Test samples=12794202 cost=0.00718997 Eval: 
I0927 12:45:51.870240 22516 TrainerInternal.cpp:162]  Batch=1200 samples=15360000 AvgCost=0.0196092 CurrentCost=0.00715693 Eval:  CurrentEval: 
I0927 12:46:28.181134 22516 TrainerInternal.cpp:162]  Batch=1500 samples=19200000 AvgCost=0.0170307 CurrentCost=0.00671664 Eval:  CurrentEval: 
I0927 12:47:38.278388 22516 TrainerInternal.cpp:162]  Batch=1800 samples=23040000 AvgCost=0.0152566 CurrentCost=0.00638629 Eval:  CurrentEval: 
I0927 12:49:04.466776 22516 Tester.cpp:111]  Test samples=12788404 cost=0.00591108 Eval: 
I0927 12:49:18.761843 22516 TrainerInternal.cpp:162]  Batch=2100 samples=26880000 AvgCost=0.0139834 CurrentCost=0.00634398 Eval:  CurrentEval: 
I0927 12:49:52.717926 22516 TrainerInternal.cpp:162]  Batch=2400 samples=30720000 AvgCost=0.0129918 CurrentCost=0.00605051 Eval:  CurrentEval: 
I0927 12:50:52.322510 22516 TrainerInternal.cpp:162]  Batch=2700 samples=34560000 AvgCost=0.0121966 CurrentCost=0.00583547 Eval:  CurrentEval: 
I0927 12:52:07.697481 22516 TrainerInternal.cpp:162]  Batch=3000 samples=38400000 AvgCost=0.0115275 CurrentCost=0.00550565 Eval:  CurrentEval: 
I0927 12:52:39.142455 22516 Tester.cpp:111]  Test samples=12788404 cost=0.00572845 Eval: 
I0927 12:53:14.013298 22516 TrainerInternal.cpp:162]  Batch=3300 samples=42240000 AvgCost=0.0109649 CurrentCost=0.00533894 Eval:  CurrentEval: 
I0927 12:54:55.922762 22516 TrainerInternal.cpp:162]  Batch=3600 samples=46080000 AvgCost=0.0104997 CurrentCost=0.00538158 Eval:  CurrentEval: 
I0927 12:55:42.010198 22516 TrainerInternal.cpp:162]  Batch=3900 samples=49920000 AvgCost=0.0101182 CurrentCost=0.00554072 Eval:  CurrentEval: 
I0927 12:56:31.666378 22516 Tester.cpp:111]  Test samples=12788404 cost=0.00569495 Eval: 
I0927 12:56:54.525758 22516 TrainerInternal.cpp:162]  Batch=4200 samples=53760000 AvgCost=0.00977327 CurrentCost=0.0052893 Eval:  CurrentEval: 
I0927 12:57:57.544978 22516 TrainerInternal.cpp:179]  Pass=0 Batch=4381 samples=56073572 AvgCost=0.00959107 Eval: 
I0927 12:58:11.957482 22516 Tester.cpp:111]  Test samples=12788404 cost=0.00567 Eval: 
I0927 12:58:11.957628 22516 GradientMachine.cpp:112] Saving parameters to ./output_dis_lr/pass-00000
I0927 12:58:11.958010 22516 Util.cpp:219] copy ./trainer_config.lr.py to ./output_dis_lr/pass-00000

Mem:  36877720k total, 36746668k used,   131052k free,    49168k buffers
Swap:  2104312k total,    48268k used,  2056044k free, 13250244k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                           
22516 user_00   20   0 26.0g  21g 8140 R 126.6 **60.8**  23:46.61 paddle_trainer

**Comment by reyoung** [comment]
@NIULQfromNJU I will add a FAQ today, and show how to reduce memory consumption. I will give the link here.

**Comment by NIULQfromNJU** [comment]
@reyoung GREAT!!

**Comment by NIULQfromNJU** [comment]
hi @backyes @reyoung 
Suppose i have a training data of 100 millions samples, and Cache=CacheType.CACHE_PASS_IN_MEM setting can not achieved in single machine with limited memory (16GB).
My dict size is about 100000, so parameter size is small.
The only question is one machine can not load all training data.
So how to solve this problem? Using Cache=CacheType.NO_CACHE ? how to train paddle models in streaming style?
thx~

**Comment by reyoung** [comment]
@NIULQfromNJU See https://github.com/baidu/Paddle/pull/128/files#diff-d718076d937b4f0e340765bf95c122c3 to preview.

**Comment by NIULQfromNJU** [comment]
hi @reyoung 
After setting pool_size and CacheType.NO_CACHE, paddle's memory cost is reduced.
Besides, i have another question: how to set the training weight of instance in paddle? thx~

**Comment by reyoung** [comment]
@NIULQfromNJU 

```
fc_layer(input=a, param_attr=ParameterAttribute(initial_std=0.5, initial_mean=0.0))
```

**Comment by NIULQfromNJU** [comment]
hi @reyoung
i means how to assign a weight for each sample, by default sample weight is 1.0. But in some case, we do down-sample training data by r, so we need to assign a weight 1/r to those samples.

**Comment by reyoung** [comment]
See #136

> i means how to assign a weight for each sample, by default sample weight is 1.0. But in some case, we do down-sample training data by r, so we need to assign a weight 1/r to those samples.
