### ISSUE TITLE
 accelerate calculation mechanism and accelerate training mechanism

### ISSUE THREAD

**Issue by shenhuinuist** [baidu/Paddle#124]
According to Paddle's documents, sparse training is usually used to accelerate calculation when input is sparse data with highly dimension,  and sparse update is not applicable to dense input. 
I find Paddle speed up matrix multiplication by calling external math libraries. Is there any accelerate calculation mechanism or accelerate training mechanism applied in Paddle especially when input is dense ? Can you show me more details?

**Comment by reyoung** [comment]
Basically, no special optimization for dense matrix.

In details, some `AVX` and `SSE` [code](https://github.com/baidu/Paddle/blob/master/paddle/math/SIMDFunctions.h) has been written  for merge gradient. In Baidu, we use `MKL` to calculate dense matrix. It is hard to write code faster than `MKL` in general.

The opensource version supports `MKL`, too. But you should buy the `MKL` license to use it. Maybe the student license is better for school usages.

**Comment by shenhuinuist** [comment]
@reyoung  Thank you so much!
