### ISSUE TITLE
the documentation of paddle is weak

### ISSUE THREAD

**Issue by CherryYin** [baidu/Paddle#125]
dotmul_operater is introduced in the documentation on layers. But there is no API about it. And "DotMulOperator" is called by "dotmul_projection", but " dotmul_projection" is as following:
```python
def dotmul_projection(input, param_attr=None, scale=1):
    if isinstance(input, LayerOutput):
        proj = DotMulProjection(input_layer_name=input.name,
                                size=input.size,
                                **param_attr.attr)
        proj.origin = input
        proj.origin.projection = "dot_mul"
        return proj
    else:
        assert isinstance(input, list) or isinstance(input, tuple)
        assert len(input) == 2
        assert_ param_attr is None
        op = DotMulOperator(input_layer_name=[x.name for x in input],
                            scale=scale)
        op.origin = input
        op.origin.operator = "dot_mul"
        return op
```
this line:assert_ param_attr is None:.
I have tried many times to give the param， but it is stll "assert"

**Comment by luotao1** [comment]
The latest version uses `DotMulOperator`, the api is http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers.html#dotmul-operator. Please update your version.
