### ISSUE TITLE
How to assign a float weight to every training sample?

### ISSUE THREAD

**Issue by NIULQfromNJU** [baidu/Paddle#136]
Is the following right?
input_types: add a dense_vector(1)
network config: add a data_layer weight=data_layer( , size=1)
cost layer: coeff=weight?

**Comment by NIULQfromNJU** [comment]
Or using scaling_layer?

**Comment by NIULQfromNJU** [comment]
hi @reyoung 
After adding a weight layer, i got the following error:
So strange, input order is not right!

![815e272f-5b5b-48b0-9fa6-1b1d414ac3bb](https://cloud.githubusercontent.com/assets/6329891/18938429/1d68e154-862b-11e6-8955-40e79251ae2e.png)
![5435f8c2-29fa-45c5-9cc6-7ea1cb85232e](https://cloud.githubusercontent.com/assets/6329891/18938430/1d6a06b0-862b-11e6-8af6-435f811a1dbd.png)
![fb1a6f37-ae16-40e4-b622-4ba64c4f138e](https://cloud.githubusercontent.com/assets/6329891/18938431/1d6a23ac-862b-11e6-9282-1d4858e7fca8.png)

**Comment by reyoung** [comment]
@NIULQfromNJU In dataprovider, we calculate the input order by reference order of `data_layer` in TrainerConfig. But user also can yield a dictionary in `dataprovider` in latest code. See `http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html#id1` 's `显式指定返回的数据对应关系`.

Sample weight should be added to cost layer. It is ok to add a`scaling_layer` to cost.  And we should add a `weight` parameter to cost layer later.

The sample config should be
``` python
feas = data_layer(name='feas', size=100)

hidden = fc_layer(input=feas, size=100)

predict = fc_layer(input=hidden, size=10, act=SoftmaxActivation())

cost = classification_cost(input=predict, label=data_layer(name='label', size=10))

cost_after_scale = scaling_layer(input=cost, weight=data_layer(name='weight', size=1))

outputs(cost_after_scale)
```

and the data provider could be

```python

def process(settings, filename):
     with open(filename) as f:
           ...
           yield { 'feas': feas, 'label': label, 'weight': weight}
```

**Comment by NIULQfromNJU** [comment]
hi @reyoung 
you mean that previous paddle (version 0.8.0b0) does not support this explicit way but the latest version?
Another question: which input_types can be used to represent the float weight? Is the following right?
# initializer
input_types=[dense_vector(1)]
# process
weight = []
weight.append(1.0)
yield weight
# config
weight=data_layer(name='weight', size=1)

thx~

**Comment by reyoung** [comment]
@NIULQfromNJU It seems that the usage above should be ok. And explicit provide data is supported since the version `0.8.0b1` .
