### ISSUE TITLE
sevearl questions about sparse training

### ISSUE THREAD

**Issue by shenhuinuist** [baidu/Paddle#137]
Hi, can you provide a demo to show how to use sparse training ? 
And according to Paddle's documentation , there are four kinds of input : dense_vector , sparse_binary_verctor, sparse_float_vector and integer, do  you take sparse_int_vector into account ? 
I find paddle implement  sparse matrix multiplication wihtout calling MKL library. I want to konw wherther the implementation of sparse matrix multiplication in paddle is faster than calling MKL library ?

**Comment by backyes** [comment]
We will provide sparse train demo with local and cluster mode in few days.

Sparse Train in PaddePaddle is beyond two sparse matrix multiplication, further implies design in Parameter Server Architecture, SGD Optimisation, etc. So it is not directly do performance comparison with only MKL library.

**Comment by shenhuinuist** [comment]
I mean that just consider the two sparse matrix multiplication, which way is faster? using MKL or  using mul function in paddle？

**Comment by backyes** [comment]
Pull request for Sparse Doc: 
https://github.com/baidu/Paddle/pull/144, which is under merging. You can preview it here: https://github.com/backyes/Paddle/blob/sparse_train/doc/demo/sparse_train/sparse_train.md

**Comment by shenhuinuist** [comment]
Thanks!
