### ISSUE TITLE
配置文档中下载docker包命名错误！

### ISSUE THREAD

**Issue by zibengou** [baidu/Paddle#16]
$ docker run -it paddledev/paddlepaddle:latest-cpu ->
$ docker run -it paddledev/paddle:cpu-latest

**Comment by ohyang326** [comment]
docker pull paddledev/paddle:cpu-latest    

tag 名字也不对。

https://hub.docker.com/r/paddledev/paddle/tags/

**Comment by emailweixu** [comment]
doc has been updated.
