### ISSUE TITLE
Recommendation demo requires docopt

### ISSUE THREAD

**Issue by alvations** [baidu/Paddle#161]
The `Paddle/demo/recommendation/` requires `docopt`, should this be added to the `*.whl`?

```
user@machine:~/Paddle/demo/recommendation$ bash preprocess.sh 
generate meta config file
Traceback (most recent call last):
  File "config_generator.py", line 29, in <module>
    import docopt
ImportError: No module named docopt
```

**Comment by reyoung** [comment]
In the [documentation of recommendation](http://www.paddlepaddle.org/doc/demo/rec/ml_regression.html#preprocess-data), it shows the command to install this dependencies.

``` bash
pip install -r requirements.txt
```

And in [requirements.txt](https://github.com/baidu/Paddle/blob/master/demo/recommendation/requirements.txt), the dependencies for this demo are listed. You can also install them one by one.

```bash
pip install PyYAML
pip install docopt
```
