### ISSUE TITLE
A protocol message was rejected because it was too big

### ISSUE THREAD

**Issue by jamestang0219** [baidu/Paddle#166]
i use LSTM model, and when i train this model, an error occurred.
I wanna know what's the problem? and how to solve it.

`I1008 06:59:43.264103 81029 Util.cpp:113] Calling runInitFunctions
I1008 06:59:43.264688 81029 Util.cpp:126] Call runInitFunctions done.
[INFO 2016-10-08 07:00:39,552 networks.py:960] The input order is [word, label]
[INFO 2016-10-08 07:00:39,553 networks.py:963] The output order is [__cost_0__]
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:171] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
F1008 07:00:44.398468 81029 TrainerConfigHelper.cpp:59] Check failed: m->conf.ParseFromString(configProtoStr)
*** Check failure stack trace: ***
    @     0x7f868e853daa  (unknown)
    @     0x7f868e853ce4  (unknown)
    @     0x7f868e8536e6  (unknown)
    @     0x7f868e856687  (unknown)
    @           0x6a8b99  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x6a8f64  paddle::TrainerConfigHelper::createFromFlags()
    @           0x53ae43  main
    @     0x7f868da5ff45  (unknown)
    @           0x546585  (unknown)
    @              (nil)  (unknown)

▽
/usr/local/bin/paddle: line 46: 81029 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}`

**Comment by jamestang0219** [comment]
I google this problem, they said because the protobuf data transmit to c++ from python is too big, is that true? if it is, and how can i fix it?

**Comment by luotao1** [comment]
how big is your dictionary?

**Comment by reyoung** [comment]
It because the `define_py_data_source`'s `args` is too large. Please shrink it and it may because your dictionary size is too large.

We may increase this limit after. Thank you for your attention.

**Comment by jamestang0219** [comment]
@luotao1 approximately 3,000,000

**Comment by reyoung** [comment]
@jamestang0219 And if you really want to train a model with 3,000,000 words. You can pass the word dictionary file path to data provider, and reload the dictionary in data provider.

**Comment by luotao1** [comment]
What's your job type? train a language model? You can paste you config here.

**Comment by jamestang0219** [comment]
@reyoung good idea, and by the way, in your quick_start project, dataprovider code:
`def process_predict(settings, file_name):
     with open(file_name, 'r') as f:
         for line in f:
             comment = line.strip()
             word_vector = [settings.word_dict.get(w, UNK_IDX) for w in comment]
             yield word_vector`

each line is a sentence string, and it doesn't need to be split? variable comment is also a sentence string not words list, for w in comment means iterate each char in this string?

**Comment by jamestang0219** [comment]
@luotao1 just follow the quick_start project, but change the train set and dictionary. Do you know is the code correct above? in word_vector, for w in comment means iterate each char in a sentence string? it doesn't need to be split?

**Comment by qingqing01** [comment]
@jamestang0219  The sentence should be splitted and I have fixed it in this pull https://github.com/baidu/Paddle/pull/168
Thanks~

**Comment by luotao1** [comment]
@jamestang0219 #168 is merged into master

**Comment by backyes** [comment]
The "big protocol message "issue is clear enough, 
@jamestang0219 can refer this pull request, all follow @reyoung suggestion to resolve it. 

Thus, close it.
