### ISSUE TITLE
Install question on ubuntu.

### ISSUE THREAD

**Issue by lilei461536135** [baidu/Paddle#178]
$sudo cmake  .. -DWITH_GPU=OFF -DWITH_DOC=OFF
-- Found PythonLibs: /usr/local/lib/libpython2.7.a (found suitable version "2.7.11", minimum required is "2.7") 
-- Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.11", minimum required is "2.7") 
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Found PythonLibs: /usr/local/lib/libpython2.7.a (found suitable version "2.7.11", minimum required is "2.6") 
-- Found PythonInterp: /usr/local/bin/python2.7 (found version "2.7.11") 
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- DROP LINT dataproviders/MultiDataProvider.cpp
-- DROP LINT dataproviders/MultiDataProvider.h
-- Could NOT find PY_pip (missing:  PY_PIP) 
CMake Error at cmake/FindPythonModule.cmake:27 (message):
  python module pip is not found
Call Stack (most recent call first):
  python/CMakeLists.txt:29 (find_python_module)

-- Configuring incomplete, errors occurred!
See also "/home/larry/workspace/paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/larry/workspace/paddle/build/CMakeFiles/CMakeError.log".

I come with the issue above. And try for long, still can't fix it. Please help!

**Comment by gangliao** [comment]
You can also simply set it as follows:

```bash
sudo cmake .. -DPY_PIP=path of your pip installed
```

**Comment by backyes** [comment]
@lilei461536135 how about your issue, 
if not done, try this: https://www.liquidweb.com/kb/how-to-install-pip-on-ubuntu-14-04-lts/

**Comment by lilei461536135** [comment]
-- Found PythonLibs: /usr/local/lib/libpython2.7.a (found suitable version "2.7.11", minimum required is "2.7") 
-- Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.11", minimum required is "2.7") 
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Found PythonLibs: /usr/local/lib/libpython2.7.a (found suitable version "2.7.11", minimum required is "2.6") 
-- Found PythonInterp: /usr/local/bin/python2.7 (found version "2.7.11") 
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Could NOT find PY_wheel (missing:  PY_WHEEL) 
CMake Error at cmake/FindPythonModule.cmake:27 (message):
  python module wheel is not found
Call Stack (most recent call first):
  cmake/check_packages.cmake:40 (find_python_module)
  CMakeLists.txt:56 (include)


-- Configuring incomplete, errors occurred!
See also "/home/larry/workspace/paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/larry/workspace/paddle/build/CMakeFiles/CMakeError.log".


Still can't Install it on my ubuntu laptop

**Comment by lilei461536135** [comment]
$ sudo pip install wheel
The directory '/home/larry/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/larry/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages

**Comment by backyes** [comment]
@lilei461536135 try  `sudo -H pip install wheel. `,  maybe you can consult internet for better answer to resolve these basic libraries installation issues.

**Comment by reyoung** [comment]
@lilei461536135 By the way if you want to install paddle on ubuntu, you can use `deb` package instead of compiling it. See [English Documentation](http://www.paddlepaddle.org/doc/build/ubuntu_install.html) or [中文文档](http://www.paddlepaddle.org/doc_cn/build_and_install/install/ubuntu_install.html).

And it seems that you install two version of python in your computer. The cmake is using python in `/usr/local/bin/python2.7`, but the pip is usint python in `/usr/lib/python2.7/` which is different from `/usr/local/lib/python2.7`. 

So, there are two ways to solve this.

* Configure the Python Binary & Library in `cmake`. Maybe you need reference these documents of cmake, [FindPythonInterp](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html) and [FindPythonLibs](https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html), and commands (not tested by myself, the directory and file path maybe wrong) may like these:

``` bash
cmake .. -D PYTHON_EXECUTABLE=/usr/bin/python2.7 -D PYTHON_LIBRARIES=/usr/lib/libpython2.7.a -D PYTHON_INCLUDE_DIRS=/usr/include/
```

* Use `/usr/local/bin/pip` to install wheel, and clean cmake build directory ( just `rm -rf *` in build directory), then rebuild should be work.

**Comment by lilei461536135** [comment]
downloaded package is incomplete. do you have a link in 百度云盘? @reyoung

**Comment by lilei461536135** [comment]
I reinstalled my ubuntu to x64 version. and finally installed paddle

**Comment by lilei461536135** [comment]
I reinstalled my ubuntu to x64 version. and finally installed paddle

**Comment by lilei461536135** [comment]
I reinstalled my ubuntu to x64 version. and finally installed paddle

**Comment by lilei461536135** [comment]
I reinstalled my ubuntu to x64 version. and finally installed paddle

**Comment by lilei461536135** [comment]
I reinstalled my ubuntu to x64 version. and finally installed paddle

**Comment by backyes** [comment]
Great.

**Comment by zbt78** [comment]
> pip install wheel

this works for me!
