### ISSUE TITLE
find a bug

### ISSUE THREAD

**Issue by bournes** [baidu/Paddle#186]
Paddle/demo/model_zoo/embedding/pre_DictAndModel.sh

here is ,,google 404......

wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/embedding/$file --no-check-certificate

**Comment by luotao1** [comment]
Maybe the firewall problem, and you can download directly from https://pan.baidu.com/s/1o8q577s instead.

**Comment by backyes** [comment]
https://github.com/baidu/Paddle/issues/160
