### ISSUE TITLE
Compilation error for ParameterClient2.cpp - Narrowing conversion

### ISSUE THREAD

**Issue by brucekissinger** [baidu/Paddle#19]
I am trying to compile Paddle on a 32-bit server running the Ubunutu 16.04.1 operating system.  The build reports 2 errors compiling pserver/Parameterclient2.cpp on line 281 and 306 stating this would result in a narrowing conversion error

**Comment by emailweixu** [comment]
Please provide the compiler version and error message. Thx.

**Comment by brucekissinger** [comment]
The gcc version is 5.4.0.20160609

Unfortunately, I don't have a good way to copy/paste the errors from the build.  I'm manually typing the messages below:

pserver/ParameterClient2.cpp:281:58: error: narrowing conversion of '(((long long unsigned int)sizeof (paddle::real)) * ((long long unsigned int)blockSize))' from 'long long unsigned int' to 'size_t {aka unsigned int}' inside { } [-Werror=narrowing]
   {sendMat->getLocalRow(row), sizeof(real) * blockSize});

the second error is:

pserver/ParameterCllent2.cpp:306:51: error: narrowing conversion of '(((uint64_t)sizeof (paddle::real)) * (endDim - beginDim))' from 'uint64_t {aka long long unsigned int}] to 'size_t {aka unsigned int}' inside { } [-Werror=narrowing]
   {buf + beginDim, sizeof(real) * (endDim - beginDim)});

**Comment by reyoung** [comment]
It seems to be the size_t in your compiler is unsigned int, not unsigned long long. We are fixing this issue.

By the way, Is gcc 5.4 supported by CUDA? Or you are just building CPU version of PaddlePaddle?

**Comment by brucekissinger** [comment]
Thank you for the extremely fast response!

Yes - I was just building the CPU version.  I'm running it on a VirtualBox instance and was not sure if access to the GPU of the underlying host machine would be possible.

**Comment by reyoung** [comment]
Current PaddlePaddle is not tested in 32bit environment. I will do the test and fix this ASAP.

**Comment by reyoung** [comment]
Sorry, I forgot to reply this issue. In fdd40e5528576899d5dd744eb772a79c53300d59, we fix 32 bit compile issues in PaddlePaddle.
