### ISSUE TITLE
How to train with Async SGD?

### ISSUE THREAD

**Issue by zuowang** [baidu/Paddle#190]
I am confused on how to train with Async SGD. 
I found there is a command line argument `--async_count`, but it's not used at all. 
Could you give me an example?

**Comment by backyes** [comment]
338 def settings(batch_size,
  339              learning_rate=1e-3,
  340              learning_method=None,
  341              regularization=None,
  342              is_async=False,
  343              model_average=None,
  344              gradient_clipping_threshold=None
  345              ):

368     :param is_async: Is Async-SGD or not. Default value is False.
369     :type is_async: bool

So, set is_asyn=True enable async-sgd. For most model, is_asyn=True is preferred

**Comment by zuowang** [comment]
Thanks!
