### ISSUE TITLE
sxi_sock.h is missing during RDMA build

### ISSUE THREAD

**Issue by ghost** [baidu/Paddle#2]
[ 86%] Building CXX object paddle/pserver/CMakeFiles/paddle_network.dir/LightNetwork.cpp.o
In file included from /usr/local/src/Paddle/paddle/pserver/LightNetwork.cpp:32:0:
/usr/local/src/Paddle/paddle/pserver/RDMANetwork.h:18:22: fatal error: sxi_sock.h: No such file or directory
 #include "sxi_sock.h"
                      ^
compilation terminated.
make[2]: **\* [paddle/pserver/CMakeFiles/paddle_network.dir/LightNetwork.cpp.o] Error 1
make[1]: **\* [paddle/pserver/CMakeFiles/paddle_network.dir/all] Error 2
make: **\* [all] Error 2

**Comment by GangLiao** [comment]
RDMA does not include in open source. To pass this, make sure WITH_RDMA=OFF.

**Comment by reyoung** [comment]
Because RDMA support should include some Baidu internal libraries and infrastructures which are not open now.  So PaddlePaddle does not support RDMA now.

**Comment by cloudaccelerator** [comment]
Thansk, do you have plans to release the RDMA support in the future?

**Comment by reyoung** [comment]
We mark this issue as a feature request, and will give the plan soon.

**Comment by backyes** [comment]
close it first, reopen it if necessary later.
