### ISSUE TITLE
cuda compiler error

### ISSUE THREAD

**Issue by holgafreak** [baidu/Paddle#20]
I'm using ubuntu 16.04 using gcc 5.4 using the hack to comment the #error in host_config.h of cuda 7.5

when building paddle, this compiler error is thrown:
[ 14%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_aggregate.cu.o
/home/xxxx/devel/paddle/paddle/cuda/src/hl_cuda_aggregate.cu: In function ‘void hl_vector_sum(paddle::real*, paddle::real*, int)’:
/home/xxxx/devel/paddle/paddle/cuda/src/hl_cuda_aggregate.cu:268:21: error: comparison of constant ‘34’ with boolean expression is always false [-Werror=bool-compare]
   } while (isNotReady == cudaErrorNotReady);

and other similar errors in the same file.

**Comment by gangliao** [comment]
We already fix this, and will update it soon. Thanks.

**Comment by gangliao** [comment]
@holgafreak  I already fixed this.
