### ISSUE TITLE
how to fix this problem when run train.sh in demo image_classification? 

### ISSUE THREAD

**Issue by Devinao** [baidu/Paddle#208]
after build and install from source code (ubuntu14.04, python2.7), according to instruction in doc.
encounter this problem as follows when run train.sh in demo/image_classification
./train.sh
First time run paddle, need to install some python dependencies.
Unpacking /home/devin/local/opt/paddle/share/wheels/paddle-0.8.0b1-py2-none-any.whl
Unpacking /home/devin/local/opt/paddle/share/wheels/py_paddle-0.8.0b1-cp27-none-linux_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): protobuf>=2.4.1 in /usr/lib/python2.7/dist-packages (from py-paddle==0.8.0b1)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.0 in /usr/lib/python2.7/dist-packages (from py-paddle==0.8.0b1)
Installing collected packages: paddle, py-paddle
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 200, in clobber
    shutil.move(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 98, in copystat
    os.utime(dst, (st.st_atime, st.st_mtime))
OSError: [Errno 1] Operation not permitted: '/usr/local/lib/python2.7/dist-packages/paddle-0.8.0b1.dist-info/WHEEL'

Storing debug log for failure in /home/devin/.pip/pip.log
pip install wheels failed. 
Please use 'sudo paddle' at the first time you use PaddlePaddle
PaddlePaddle will install some python dependencies automatically.
No data to plot. Exiting!

someone can tell me how to fix it？ 3ks!

**Comment by lilei461536135** [comment]
maybe you should install wheel module in python firstly

**Comment by Devinao** [comment]
@lilei461536135 it's already installed, so something else?

**Comment by gangliao** [comment]
You can simply typing `sudo paddle version` to install python wheel.

or you can issue the following commands:
```
# you can run
sudo pip install <path to install>/opt/paddle/share/wheels/*.whl
```

**Comment by backyes** [comment]
@Devinao this should be BUG, PaddlePaddle will delay install related python library until 'paddle' command firstly starts. However the delayed python installation also needs sudo permission.  @gangliao's solution can avoid this BUG, while your 'train.sh' indirectly call 'paddle' command and trigger this BUG. 
We will try to revise this solution and fix this later. You can just follow @gangliao 's way to skip it.

**Comment by zuowang** [comment]
@gangliao 
The above error is bypassed with `sudo paddle`, but I ran into below error:

F1025 09:16:26.811064  3217 PythonUtil.h:148] Check failed: (obj) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/usr/local/lib/python2.7/dist-packages/paddle-0.8.0b-py2.7.egg', '/home/paddle/JOB20161025091555', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
Python Error: <type 'exceptions.AttributeError'> : 'DataProvider' object has no attribute 'min_pool_size'
Python Callstack:
Cannot get attribute on python object 0x7f0c06b52050
*** Check failure stack trace: ***
    @     0x7f0c05a0bdaa  (unknown)
    @     0x7f0c05a0bce4  (unknown)
    @     0x7f0c05a0b6e6  (unknown)
    @     0x7f0c05a0e687  (unknown)
    @           0xa54c5c  paddle::py::ObjectHelper::getAttr()
    @           0xa5c556  paddle::py::ObjectHelper::getIntAttr<>()
    @           0xa56eb2  paddle::PyDataProvider2::readPyFields()
    @           0xa55f3f  paddle::PyDataProvider2::PyDataProvider2()
    @           0xa5dc92  _ZZN6paddle14ClassRegistrarINS_12DataProviderEINS_10DataConfigENS_11ModelConfigEbEE13registerClassINS_15PyDataProvider2EEEvRKSsENKUlS2_S3_bE_clES2_S3_b
    @           0xa62276  _ZNSt17_Function_handlerIFPN6paddle12DataProviderENS0_10DataConfigENS0_11ModelConfigEbEZNS0_14ClassRegistrarIS1_IS3_S4_bEE13registerClassINS0_15PyDataProvider2EEEvRKSsEUlS3_S4_bE_E9_M_invokeERKSt9_Any_dataS3_S4_b
    @           0xa9aff5  std::function<>::operator()()
    @           0xa9a17f  paddle::ClassRegistrar<>::createByType()
    @           0xa940fb  paddle::DataProvider::create()
    @           0xb3572b  paddle::Trainer::init()
    @           0x96e10b  main
    @     0x7f0c04c17f45  (unknown)
    @           0x96d5b9  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 81:  3217 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
@zuowang Start a new issues please
