### ISSUE TITLE
No data to plot after run image_classification demo

### ISSUE THREAD

**Issue by lilei461536135** [baidu/Paddle#209]
larry@L~eBook:~/Documents/Paddle/Paddle-master/demo/image_classification$ sh train.sh 
I1015 11:51:56.208109  7998 Util.cpp:151] commandline: /usr/bin/../opt/paddle/bin/paddle_trainer --config=vgg_16_cifar.py --dot_period=10 --log_period=100 --test_all_data_in_one_period=1 --use_gpu=0 --trainer_count=1 --num_passes=200 --save_dir=./cifar_vgg_model 
I1015 11:51:56.208637  7998 Util.cpp:126] Calling runInitFunctions
I1015 11:51:56.209271  7998 Util.cpp:139] Call runInitFunctions done.
[INFO 2016-10-15 11:51:56,626 layers.py:1620] channels=3 size=3072
[INFO 2016-10-15 11:51:56,627 layers.py:1620] output size for __conv_0__ is 32 
[INFO 2016-10-15 11:51:56,632 layers.py:1620] channels=64 size=65536
[INFO 2016-10-15 11:51:56,633 layers.py:1620] output size for __conv_1__ is 32 
[INFO 2016-10-15 11:51:56,638 layers.py:1681] output size for __pool_0__ is 16*16 
[INFO 2016-10-15 11:51:56,641 layers.py:1620] channels=64 size=16384
[INFO 2016-10-15 11:51:56,641 layers.py:1620] output size for __conv_2__ is 16 
[INFO 2016-10-15 11:51:56,646 layers.py:1620] channels=128 size=32768
[INFO 2016-10-15 11:51:56,647 layers.py:1620] output size for __conv_3__ is 16 
[INFO 2016-10-15 11:51:56,651 layers.py:1681] output size for __pool_1__ is 8*8 
[INFO 2016-10-15 11:51:56,653 layers.py:1620] channels=128 size=8192
[INFO 2016-10-15 11:51:56,654 layers.py:1620] output size for __conv_4__ is 8 
[INFO 2016-10-15 11:51:56,659 layers.py:1620] channels=256 size=16384
[INFO 2016-10-15 11:51:56,660 layers.py:1620] output size for __conv_5__ is 8 
[INFO 2016-10-15 11:51:56,663 layers.py:1620] channels=256 size=16384
[INFO 2016-10-15 11:51:56,664 layers.py:1620] output size for __conv_6__ is 8 
[INFO 2016-10-15 11:51:56,667 layers.py:1681] output size for __pool_2__ is 4*4 
[INFO 2016-10-15 11:51:56,668 layers.py:1620] channels=256 size=4096
[INFO 2016-10-15 11:51:56,669 layers.py:1620] output size for __conv_7__ is 4 
[INFO 2016-10-15 11:51:56,672 layers.py:1620] channels=512 size=8192
[INFO 2016-10-15 11:51:56,672 layers.py:1620] output size for __conv_8__ is 4 
[INFO 2016-10-15 11:51:56,675 layers.py:1620] channels=512 size=8192
[INFO 2016-10-15 11:51:56,676 layers.py:1620] output size for __conv_9__ is 4 
[INFO 2016-10-15 11:51:56,678 layers.py:1681] output size for __pool_3__ is 2*2 
[INFO 2016-10-15 11:51:56,679 layers.py:1681] output size for __pool_4__ is 1*1 
[INFO 2016-10-15 11:51:56,685 networks.py:1125] The input order is [image, label]
[INFO 2016-10-15 11:51:56,685 networks.py:1132] The output order is [__cost_0__]
I1015 11:51:56.701963  7998 Trainer.cpp:170] trainer mode: Normal
I1015 11:51:56.746357  7998 PyDataProvider2.cpp:247] loading dataprovider image_provider::processData
[INFO 2016-10-15 11:51:56,946 image_provider.py:52] Image size: 32
[INFO 2016-10-15 11:51:56,946 image_provider.py:53] Meta path: data/cifar-out/batches/batches.meta
[INFO 2016-10-15 11:51:56,946 image_provider.py:58] DataProvider Initialization finished
I1015 11:51:56.947093  7998 PyDataProvider2.cpp:247] loading dataprovider image_provider::processData
[INFO 2016-10-15 11:51:56,968 image_provider.py:52] Image size: 32
[INFO 2016-10-15 11:51:56,969 image_provider.py:53] Meta path: data/cifar-out/batches/batches.meta
[INFO 2016-10-15 11:51:56,969 image_provider.py:58] DataProvider Initialization finished
I1015 11:51:57.007619  7998 GradientMachine.cpp:134] Initing parameters..
I1015 11:51:57.599355  7998 GradientMachine.cpp:141] Init parameters done.
/usr/bin/paddle: line 81:  7998 Killed                  ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
No data to plot. Exiting!

Does process 7998 killed normally?

**Comment by backyes** [comment]
Maybe PaddlePaddle exhaust too many memories and your laptop system just kill this process... Generally, linux system will kill process eating too may memories...

**Comment by lilei461536135** [comment]
@backyes 4GB memory on this laptop. Too less for it?

**Comment by backyes** [comment]
Observe the memory available while starting PaddlePaddle using cat /proc/meminfo.

**Comment by lilei461536135** [comment]
@backyes  It eats too many memories, almost no free memory to use for system. And even screen become black.

**Comment by backyes** [comment]
If you just want to use this demo to help to understand how it works, try hacking default parameter layer size to reduce model size..
