### ISSUE TITLE
Follow the build instructions, but fails in the build directory

### ISSUE THREAD

**Issue by wangmiao1981** [baidu/Paddle#23]
I tried:
git clone https://github.com/baidu/Paddle paddle
cd paddle
mkdir build
cd build
cmake -DWITH_GPU=OFF -DWITH_DOC=OFF
CMake Error: The source directory "/home/mwang/paddle_src/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

I can only do cmake in the parent folder and build the package succesfully.

**Comment by stoneyang** [comment]
It seem that you forgot the `..` when you build PaddlePaddle under the build directory.

**Comment by wangmiao1981** [comment]
Yes. Add .. cmake works fine.

Then, I copy "make -j `nproc` && make install" in the document.

make: *** No targets specified and no makefile found.  Stop.

The document should add "cd .." before make? I can build successfully outside build folder.

Or I make another mistake?

**Comment by gangliao** [comment]
http://www.paddlepaddle.org/doc/build/build_from_source.html

Do you follow the build from source page and set make install path?

`git clone https://github.com/baidu/Paddle paddle
cd paddle
mkdir build
cd build
# you can add build option here, such as:    
cmake -DWITH_GPU=ON -DWITH_DOC=OFF -DCMAKE_INSTALL_PREFIX=<path to install> ..
make -j `nproc` && make install
# PaddlePaddle installation path
export PATH=<path to install>/bin:$PATH`

**Comment by stoneyang** [comment]
@wangmiao1981 seems that no Makefile's generated by cmake. 
You should check against the steps provided by @gangliao with yours and mind whether the Makefile's generated after `cmake -DWITH_GPU=OFF -DWITH_DOC=OFF ..` and under the very build directory, just proceed:
```
# if one would like to install PaddlePaddle into the system, sudo before make install should be added
make -j `nproc` && make install
```

**Comment by wangmiao1981** [comment]
Yes. I built successfully once and installed it. Then, I check out a branch and try to play with it.

For that branch, I did compile again without installation. Then, I made once mistake by missing `..` in the cmake. After fix that, I type `make -j `nproc`` inside build fold and saw the error above.
