### ISSUE TITLE
when i ran the demo Sentiment Analysis,error happened

### ISSUE THREAD

**Issue by hdulbj** [baidu/Paddle#233]
I install the paddlepaddle successfully which is built from the source 
after that i wanted to run the demo Sentiment Analysis,and i did as the Tutorial said
but when i run ./train.sh,the error happened

[lbj@gpu001 data]$ ls
aclImdb  aclImdb_v1.tar.gz  get_imdb.sh  get_imdb.sh_bak  imdb  master  mosesdecoder-master  pre-imdb
[lbj@gpu001 data]$ cd ..
[lbj@gpu001 sentiment]$ ls
data             predict.py  preprocess.py  sentiment_net.py   test.sh            train.log
dataprovider.py  predict.sh  preprocess.sh  sentiment_net.pyc  trainer_config.py  train.sh
[lbj@gpu001 sentiment]$ ./train.sh 
I1022 01:20:25.624637  4116 Util.cpp:155] commandline: /home/lbj/paddle/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=false --trainer_count=4 --num_passes=10 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1 
I1022 01:20:25.624955  4116 Util.cpp:130] Calling runInitFunctions
I1022 01:20:25.625247  4116 Util.cpp:143] Call runInitFunctions done.
[INFO 2016-10-22 01:20:25,950 networks.py:1145] The input order is [word, label]
[INFO 2016-10-22 01:20:25,951 networks.py:1152] The output order is [__cost_0__]
I1022 01:20:25.954066  4116 Trainer.cpp:170] trainer mode: Normal
*** Aborted at 1477070425 (unix time) try "date -d @1477070425" if you are using GNU date ***
PC: @           0x761fb2 paddle::Weight::Weight()
*** SIGSEGV (@0xe8) received by PID 4116 (TID 0x7f89114cf740) from PID 232; stack trace: ***
    @       0x32aba0f520 (unknown)
    @           0x761fb2 paddle::Weight::Weight()
    @           0x5ca099 paddle::TableProjection::TableProjection()
    @           0x5cae83 _ZNSt17_Function_handlerIFPN6paddle10ProjectionENS0_16ProjectionConfigESt10shared_ptrINS0_9ParameterEEbEZNS0_14ClassRegistrarIS1_JS3_S6_bEE13registerClassINS0_15TableProjectionEEEvRKSsEUlS3_S6_bE_E9_M_invokeERKSt9_Any_dataS3_S6_b
    @           0x5c9254 paddle::Projection::create()
    @           0x5e4a3a paddle::MixedLayer::init()
    @           0x53792f paddle::NeuralNetwork::init()
    @           0x519f38 paddle::MultiGradientMachine::MultiGradientMachine()
    @           0x51325e paddle::GradientMachine::create()
    @           0x668b75 paddle::TrainerInternal::init()
    @           0x664457 paddle::Trainer::init()
    @           0x5121d5 main
    @       0x32ab61f84d (unknown)
    @           0x510c19 (unknown)
/home/lbj/paddle/bin/paddle: line 81:  4116 段错误               (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

So what's wrong with it?

**Comment by qingqing01** [comment]
I wondered that there is some problem with your data processing. As mentioned in the document http://www.paddlepaddle.org/doc/demo/sentiment_analysis/sentiment_analysis.html#imdb-data-preparation,  if running successfully, you will see demo/sentiment/data/pre-imdb directory as follows:
```
dict.txt  labels.list  test.list  test_part_000  train.list  train_part_000
```

Then, the successful training will print the dictionary length in `dataprovider.py `, like:

```
I1021 22:52:17.607539 31046 Util.cpp:155] commandline: /home/tools/paddle/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=false --trainer_count=4 --num_passes=10 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1
I1021 22:52:17.607754 31046 Util.cpp:130] Calling runInitFunctions
I1021 22:52:17.608122 31046 Util.cpp:143] Call runInitFunctions done.
[INFO 2016-10-21 22:52:18,073 networks.py:1285] The input order is [word, label]
[INFO 2016-10-21 22:52:18,074 networks.py:1292] The output order is [__cost_0__]
I1021 22:52:18.151166 31046 Trainer.cpp:170] trainer mode: Normal
I1021 22:52:18.922603 31046 PyDataProvider2.cpp:247] loading dataprovider dataprovider::process
[INFO 2016-10-21 22:52:18,923 dataprovider.py:22] dict len : 101745
I1021 22:52:19.022967 31046 PyDataProvider2.cpp:247] loading dataprovider dataprovider::process
[INFO 2016-10-21 22:52:19,023 dataprovider.py:22] dict len : 101745
I1021 22:52:19.023491 31046 GradientMachine.cpp:134] Initing parameters..
I1021 22:52:19.873340 31046 GradientMachine.cpp:141] Init parameters done.
```

But, your error message does not show the dictionary length. So, please check your data.

Thanks~

**Comment by hdulbj** [comment]
thx!!!
the preprocess data failed because of lack of perl module,and i did'nt notice it.

**Comment by reyoung** [comment]
Or maybe we should check preprocess running success @qingqing01
