### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by lixx1746** [baidu/Paddle#24]
Hi,
When building paddle with gcc4.8.2, there is an error:
Building CXX object paddle/utils/CMakeFiles/paddle_utils.dir/PythonUtil.cpp.o
/usr/local/include/python2.7/pyport.h:871:76: error: 'PyArg_ParseTuple' is an unrecognized format function type [-Werror=format=]

Thanks.

**Comment by qingqing01** [comment]
@lixx1746 Hi, maybe, you can add "-Wformat" in paddle/cmake/flags.cmake like:

`set(COMMON_FLAGS
    -fPIC
    -fno-omit-frame-pointer
    -Wall
    -Wextra
    -Werror
    **-Wformat**
    -Wnon-virtual-dtor
    -Wdelete-non-virtual-dtor
    -Wno-unused-parameter
    -Wno-error=literal-suffix
    -Wno-error=unused-local-typedefs)`

And I refer this [link] (https://bugs.python.org/issue17547).

**Comment by lixx1746** [comment]
@qingqing01 Thank you so much. But it still doesn't work.

**Comment by reyoung** [comment]
@lixx1746 You actually use docker image to use PaddlePaddle without build it.  Links are https://hub.docker.com/r/paddledev/paddle/tags/

**Comment by gangliao** [comment]
You can PaddlePaddle's Docker Image to dig deeper too. If you still want to compile code locally, 
maybe the following two ways will help you: 

1. Using -Wno-format to bypass this problem.
or
2. you can either upgrade or downgrade you python.

**Comment by emailweixu** [comment]
There is related problem here. https://bugzilla.redhat.com/show_bug.cgi?id=927358. Perhaps you can try update your python2.7.

**Comment by lixx1746** [comment]
Thank you guys, I fix it with -Wno-format.
