### ISSUE TITLE
Python Error: : 'DataProvider' object has no attribute 'min_pool_size'

### ISSUE THREAD

**Issue by zuowang** [baidu/Paddle#245]
git checkout commit 9c5c38fa
build and install on ubuntu14.04 with python2.7
run train.sh in demo/image_classification

I got below error:

F1025 09:16:26.811064 3217 PythonUtil.h:148] Check failed: (obj) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/usr/local/lib/python2.7/dist-packages/paddle-0.8.0b-py2.7.egg', '/home/paddle/JOB20161025091555', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
Python Error: : 'DataProvider' object has no attribute 'min_pool_size'
Python Callstack:
Cannot get attribute on python object 0x7f0c06b52050
*** Check failure stack trace: ***
@ 0x7f0c05a0bdaa (unknown)
@ 0x7f0c05a0bce4 (unknown)
@ 0x7f0c05a0b6e6 (unknown)
@ 0x7f0c05a0e687 (unknown)
@ 0xa54c5c paddle::py::ObjectHelper::getAttr()
@ 0xa5c556 paddle::py::ObjectHelper::getIntAttr<>()
@ 0xa56eb2 paddle::PyDataProvider2::readPyFields()
@ 0xa55f3f paddle::PyDataProvider2::PyDataProvider2()
@ 0xa5dc92 _ZZN6paddle14ClassRegistrarINS_12DataProviderEINS_10DataConfigENS_11ModelConfigEbEE13registerClassINS_15PyDataProvider2EEEvRKSsENKUlS2_S3_bE_clES2_S3_b
@ 0xa62276 _ZNSt17_Function_handlerIFPN6paddle12DataProviderENS0_10DataConfigENS0_11ModelConfigEbEZNS0_14ClassRegistrarIS1_IS3_S4_bEE13registerClassINS0_15PyDataProvider2EEEvRKSsEUlS3_S4_bE_E9_M_invokeERKSt9_Any_dataS3_S4_b
@ 0xa9aff5 std::function<>::operator()()
@ 0xa9a17f paddle::ClassRegistrar<>::createByType()
@ 0xa940fb paddle::DataProvider::create()
@ 0xb3572b paddle::Trainer::init()
@ 0x96e10b main
@ 0x7f0c04c17f45 (unknown)
@ 0x96d5b9 (unknown)
@ (nil) (unknown)
/usr/local/bin/paddle: line 81: 3217 Aborted (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
It seems you should uninstall paddle python package before.

Do

```
pip uninstall -y paddle py_paddle
```

**Comment by reyoung** [comment]
And maybe we should make a better version system.

**Comment by zuowang** [comment]
Thanks!
