### ISSUE TITLE
Mistake in demo/image_classification/preprocess.sh 

### ISSUE THREAD

**Issue by xiangqiaolxq** [baidu/Paddle#25]
A mistake in preprocess.sh line 17 "export PYTHONPATH=$PYTHONPATH:../../"
In this path ,can't find python module.
export path shoule be inplace with  PYTHONPATH=$PYTHONPATH:../../python"

**Comment by stoneyang** [comment]
See my PR #11 :)

**Comment by reyoung** [comment]
#11 duplicated

**Comment by stoneyang** [comment]
@reyoung ?
