### ISSUE TITLE
Switch to Git branching model

### ISSUE THREAD

**Issue by wangkuiyi** [baidu/Paddle#250]
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by reyoung** [comment]
https://github.com/nvie/gitflow command line tools

**Comment by reyoung** [comment]
Update docs with #275 . Done.

**Comment by wangkuiyi** [comment]
#275 说明的内容看上去并没有解决这个issue。

如果转换成了新的git branching model，那么 master branch 里应该只包含 release commits。但是我在 [Network 页面](https://github.com/baidu/Paddle/network)里看到的是 master branch 里有很多各种各样的 commits。

我前天成功地把一个只有一个主干的开源项目 [Sextant](https://github.com/k8sp/sextant/) 变成了双主干。我发现其中有不少坑，需要注意的。我把我的做法详细地描述在[这篇wiki](https://github.com/k8sp/sextant/wiki/%E7%BB%99Github%E4%B8%8A%E7%9A%84%E9%A1%B9%E7%9B%AE%E5%8A%A0%E4%B8%8A%E5%8F%8C%E4%B8%BB%E5%B9%B2)里了。供参考。

**Comment by reyoung** [comment]
重写已经被广泛fork的版本库的历史是一件非常有风险的事情。因为本质上只能重新中央版本库的历史，而其他fork的commits便会成为没有主线的commits。所以，感觉似乎不应该删除旧的master分支。

如果有新的release的话，就在master分支之后再加新的commit吧

**Comment by reyoung** [comment]
另外，paddle的release不只是tag，还有同时发布的二进制。所以，如果把master先删掉，所有的二进制是否还会存在。这个也是个问题。

**Comment by wangkuiyi** [comment]
binary应该是根据git commit生成的吧。如果是这样，那么因为删除branch并不会删除commits，所以所有的binaries还是有效的。

**Comment by wangkuiyi** [comment]
这个工作和fork没有关系。已经产生的forks是被用在未来的开发里的，所以不受“篡改历史”的影响。未来新的fork会包含“篡改过的历史”。

**Comment by reyoung** [comment]
@wangkuiyi Done. There just three commits in master network now(init, V0.8.0b0, V0.8.0b1)

https://github.com/baidu/Paddle/network

Although I use a slightly different way to do it. I just checkout an orphan branch, create a new root commit with some empty file (.gitignore, README.md), and merge each tags to this branch. 

Also rewrite the commit time to make github network more pretty.

**Comment by wangkuiyi** [comment]
This is awesome! Thanks! @reyoung 

Although it seems more reasonable to make the master branch starting from the initial commit other than an orphan commit, e.g., https://github.com/k8sp/sextant/network, but this fits what we need, and I like it as much as the other way.
