### ISSUE TITLE
Separate source code

### ISSUE THREAD

**Issue by wangkuiyi** [baidu/Paddle#251]
Currently, there are two copies of Paddle source code -- one on Github, the other one on a Baidu internal Git repo -- and someone periodically merges Github repo to the internal repo. This is error-prone and unnecessary. The team decided to maintain only the Github repo.

**Comment by backyes** [comment]
Task： 

* split iternal platform to separate repo (assign @backyes )
* split RDMA as sub module (assign @backyes)

* clean metric learning and other third party internal module (?? @reyoung ) 

@wangkuiyi

**Comment by reyoung** [comment]
The metric learning & another internal layers are not urgency to split out. The old repo will be archived. 

We should find out how to make Paddle layer as a runtime plugin firstly, then separate the internal layers into multiple plugins. It should be a long term discussion and couldn't be done in 2 weeks.

So task three will not be done in this milestone.

**Comment by backyes** [comment]
已分离出：
* 内部platform2 repository （供集群使用）
* 内部一键release tools （供单机使用）
其他metric learning等暂时hold。

这里先close这个关联milestone的issue。
