### ISSUE TITLE
Integrate pep8 for Python code style checking

### ISSUE THREAD

**Issue by wangkuiyi** [baidu/Paddle#254]
https://pypi.python.org/pypi/pep8

**Comment by QiJune** [comment]
I find a useful open source tool created by google, yapf  https://github.com/google/yapf
 `pip install yapf`  will install yapf tool.
This tool provides 4 based style to choose: pep8, google, facebook and chromium.
The style can be find in this link. https://github.com/google/yapf/blob/master/yapf/yapflib/style.py

I make some python code formatting test on currently code on github
Here is a .style.yapf config file created in paddle directory:
```
[style]
based_on_style = google
indent_width = 4
spaces_before_comment = 4
split_before_logical_operator = true
``` 
After run `yapf -r -i python/`, the python code will be formatted.
But, it brings so much diff and changes our python code format.
Should we format the code right now, or just add a yapf config file?

**Comment by reyoung** [comment]
basically done, closed
