### ISSUE TITLE
support static link for almost dependency libraries for easy installation. 

### ISSUE THREAD

**Issue by backyes** [baidu/Paddle#259]
- enable CMAKE support static link for most libraries, except core GLIBC.  
- try to enable full static link for most platform

**Comment by backyes** [comment]
已经产出内部用户一键编译工具：
* 对除gcc运行时库之外的所有第三方库均采用静态编译
* 已实现二进制包发布

这里关闭此issue。

**Comment by reyoung** [comment]
这个事情，我想有百度内和社区两个方面，

一个是百度公司内的问题，我们已经使用用纯静态二进制分发了Paddle。请确保用户都知道了静态二进制的存在，特别是，我们应该修改内网的一些连接到静态的二进制包上。或者维护一个release页面，让用户能够找到二进制的下载地址。

另一个是，对社区来说，我也觉得使用Docker或者安装包就够了。

**Comment by wangkuiyi** [comment]
我赞同发布docker image即可。可以close这个issue。
