### ISSUE TITLE
Does paddle paddle support python 3 ? Is there a way to import paddle package with python 3 in anaconda in docker?

### ISSUE THREAD

**Issue by kitianFresh** [baidu/Paddle#264]

**Comment by reyoung** [comment]
Currently, `Python 3` is not supported, only `Python 2` is supported.

Is there any package you want to use in python 3?

**Comment by kitianFresh** [comment]
Yes， i want to use aiohttp

**Comment by wangkuiyi** [comment]
@reyoung How about we list the reasons that we don't support Python 3 somewhere, and paste a link here, so that the community knows the status and might contribute?

**Comment by reyoung** [comment]
`Python 2` currently is the most widely used version of python now. And `Paddle` is embedded a Python interpreter inside C++ part. See [PythonUtil](https://github.com/baidu/Paddle/blob/master/paddle/utils/PythonUtil.h), [PyDataProvider2](https://github.com/baidu/Paddle/blob/master/paddle/gserver/dataproviders/PyDataProvider2.cpp). So `Paddle` is heavily depends on `CPython API` which might be changed in `Python 3`.

To support `Python 3`, we need rewrite some C++ code in Paddle to make sure it support both `Python 2` and `3`. It currently not in our plan, but if this feature is needed very widely, we will consider to add this support to our recently milestones.

And @kitianFresh , the `aiohttp` package, I just google and found that it is used for async http client, which [tornado](http://www.tornadoweb.org/en/stable/httpclient.html) might be able to do the same thing, but support `python 2`.

**Comment by kitianFresh** [comment]
@reyoung Thanks for the answer ! I am new for python. I only used aiohttp for async but no other framework experience, so i just want to save my time to focus on  machine learning! I wish you will support python 3 soon because tensorflow have supported it ! I will research for tornado! thanks!
