### ISSUE TITLE
demo/sentiment_analysis/ 这部分是没有翻译吧，我想认领翻译可以吗？

### ISSUE THREAD

**Issue by westeast** [baidu/Paddle#270]
demo/sentiment_analysis/ 这部分是没有翻译吧，我想认领翻译可以吗？

**Comment by westeast** [comment]
怎么认领呢？

**Comment by gangliao** [comment]
If you plan is scheduled very well, you can connect this issue with recent milestone. Thanks.

**Comment by reyoung** [comment]
@westeast The documentation is written in sphinx, and use `cmake` to compile. I will write a documentation for `how to write Paddle's docs` ASAP.

**Comment by westeast** [comment]
@reyoung I am looking forward to your documentation :)

**Comment by wangkuiyi** [comment]
@reyoung Sphinx有很细致的[文档](http://www.sphinx-doc.org/en/1.4.8/tutorial.html)。如果为Paddle写文档的过程不是很复杂，只有几个操作步骤的话，就不需要通过PR新增文档了，直接写在这里， @westeast 就可以开始工作了吧。

如果有什么遗漏的信息， @westeast 也可以在这里提出来。等 @westeast 的第一个文档贡献结束折后，这个 issue 里也沉淀了足够的信息，可以请 @westeast （如果有兴趣的话）来写一篇 Paddle Documentation Howto.

多谢 @westeast 的贡献！

**Comment by westeast** [comment]
@wangkuiyi ok,no problem

**Comment by westeast** [comment]
@reyoung 你好，这是我的翻译：https://github.com/westeast/Paddle/blob/master/doc_cn/demo/sentiment_analysis/sentiment_analysis.md
我是把sentiment_analysis这个目录从doc目录复制到了doc_cn目录来翻译的，帮确认下是否可以pr到这里或者还需要做其它什么工作。

**Comment by luotao1** [comment]
你可以提一个PR，图片请用软连接，不用复制一遍

**Comment by Haichao-Zhang** [comment]
@westeast <https://github.com/westeast> 最后一句： 参于贡献 => 参与贡献

**Comment by westeast** [comment]
@luotao1 好的，我修改下,图片用doc目录的。然后改点细节后提个pr
@Haichao-Zhang 多谢指出，我修改下。
