### ISSUE TITLE
Gflag problem when compiling paddle

### ISSUE THREAD

**Issue by CrossLee1** [baidu/Paddle#274]
When I compile paddle with cmake, the following errors occur:

```
CMake Error at /home/lib/cmake/gflags/gflags-export.cmake:16 (ADD_LIBRARY):
  add_library cannot create imported target "gflags-static" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /home/lib/cmake/gflags/gflags-config.cmake:10 (include)
  cmake/FindGflags.cmake:318 (find_package)
  cmake/check_packages.cmake:22 (find_package)
  CMakeLists.txt:53 (include)

CMake Error at /home/lib/cmake/gflags/gflags-export.cmake:19 (ADD_LIBRARY):
  add_library cannot create imported target "gflags_nothreads-static" because
  another target with the same name already exists.
Call Stack (most recent call first):
  /home/lib/cmake/gflags/gflags-config.cmake:10 (include)
  cmake/FindGflags.cmake:318 (find_package)
  cmake/check_packages.cmake:22 (find_package)
  CMakeLists.txt:53 (include)
```

How to solve this problem? Thanks~

**Comment by reyoung** [comment]
@CrossLee1 
How does you run `cmake` command? 

If you want to use Paddle, we recommend you to use Docker images, or install packages. To build Paddle from source, we suggest you follow our building guide.

Please record an [asciinema](https://asciinema.org/) to us, so we can dig out much more details about this error.

**Comment by CrossLee1** [comment]
@reyoung 
I simply use this command `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SWIG_PY=ON ..`

BTW, if I set -DWITH_GFLAGS=OFF, does if affect the functions of paddle?

**Comment by reyoung** [comment]
@CrossLee1 `WITH_GFLAGS=OFF` is OK for basically usage. But `WITH_GFLAGS=OFF` the command line is slightly different from `GFlags`. It only supports `--flag=something`, not supports `--flag something`.

It is very kind if you have time to record an asciinema for us to figure out why this errors happened.

**Comment by wangkuiyi** [comment]
@CrossLee1 可否贴一下你执行的命令，以及它们输出的结果 ——  也就是 @reyoung 说的 asciinema。这样便于其他人复现和定位问题。现在这样 ——  @reyoung 猜测问题所在，逐个提问，效率很低，而且可能错过了重要依据。

**Comment by reyoung** [comment]
No response for too long, closed.
