### ISSUE TITLE
train.sh in semantic_role_labeling cannot exit at the end

### ISSUE THREAD

**Issue by byzhang** [baidu/Paddle#286]
It hangs when the last pass is trained, for the following settings:
1. use_gpu = false, trainer_count=4
2. use_gpu = true, trainer_count=4 
3. use_gpu = true, trainer_count=1

It can exit normally only when
4. use_gpu = false, trainer_count=1

**Comment by byzhang** [comment]
I'm at @9c5c38f

**Comment by pineking** [comment]
+1

**Comment by wangkuiyi** [comment]
这个问题我也碰到过。请 @reyoung 看看谁来解决合适。

此外，我们的值班表 https://github.com/baidu/Paddle/wiki/Paddle-Members-on-Duty 里没有安排周末值班。这会导致我们对周末提出的需求的相应变慢，也会导致周一的值班员的工作任务太重。

我可以来担任周末值班员，但是我对项目情况还不够熟悉，周末可能会Hi大家。

**Comment by reyoung** [comment]
Thank you for response. I'm trying to fix it.
