### ISSUE TITLE
Is this OK to install requirements from source ?

### ISSUE THREAD

**Issue by NIULQfromNJU** [baidu/Paddle#29]
When build on Ubuntu, paddle's requirements(cmake, protobuf, blas, etc.) can be installed using following way: 
# sudo apt-get install -y g++ make cmake build-essential libatlas-base-dev python python-pip libpython-dev m4 libprotobuf-dev protobuf-compiler python-protobuf python-numpy git 

But if i want to build paddle on other platform which can not connect to internet, the only way is to build these requirements(cmake, g++, blas, protobuf, python) from downloaded source code. 

So i want to confirm is this ok to install these requirements from source.

thanks~

**Comment by emailweixu** [comment]
It should be ok.

**Comment by reyoung** [comment]
And please note that we use protobuf version 2, not version 3.

**Comment by NIULQfromNJU** [comment]
thanks, guys~
