### ISSUE TITLE
Automatically assign reviewers for Pull Requests or Issues

### ISSUE THREAD

**Issue by reyoung** [baidu/Paddle#298]
It seems that facebook opensource a very lightweight tool to automatically mention potential reviewers for a PR, due to `git blame` command to figure out the related author, or set reviewers by matching path of repo. Such as the `/paddle/cuda` should be mention to @hedaoyuan .

The project is [here](https://github.com/facebook/mention-bot).

We could also write a robot to mention people to response issues.

**Comment by wangkuiyi** [comment]
I agree. And I'd welcome any tools that can automate our engineering process. Please go on and do it! Thanks! @reyoung

**Comment by reyoung** [comment]
Done for issue robot

**Comment by reyoung** [comment]
The github issues of Paddle are watched by [GhIssueBot](https://github.com/reyoung/GhIssueBot), and email will be sent to someone who is on duty when github issue **open**, **reopen**, **new comment**.

It might be buggy because lack of unittest, but currently it works well.

**Comment by wangkuiyi** [comment]
Thanks to @reyoung !
