### ISSUE TITLE
  求 AucValidation  的使用实例配置

### ISSUE THREAD

**Issue by buptzzl** [baidu/Paddle#305]

**Comment by zhouxiao-coder** [comment]
AucValidation is implemented as an evaluator. It's often used in binary classification problems.

A simple usage:
```
eval = auc_evaluator(input, label)
```
where `input` is the prediction of your network, and `label` is the true label. For usages of other evaluators, you can check out this page: [PaddlePaddle documentation](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/evaluators.html#auc-evaluator)

**Comment by buptzzl** [comment]
吐槽一下： 为何 在 conf 文件里需要的名字和 文档里写的Layer的名字不一样呢？ 这样看了文档反而导致错误的配置！

**Comment by luotao1** [comment]
请问conf需要的名字和文档里写的layer名字分别是什么？

**Comment by buptzzl** [comment]
@luotao1   介绍Layer的文档写的是 AucValidation ，
而写PY的CONF文件时则要用 eval = auc_evaluator(input, label)

**Comment by zhouxiao-coder** [comment]
@buptzzl 
AucValidation 似乎是旧接口中的名字，如果你看的是百度内网上的文档的话可能会看到。未来统一都会使用新的接口，所以文档参照的话建议看 http://www.paddlepaddle.org/doc/ 。
当然，有使用过程有任何问题都欢迎吐槽：）
