### ISSUE TITLE
Check failed: connect(sockfd, (sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR connecting to xxxxxxx: Connection refused

### ISSUE THREAD

**Issue by 20092136** [baidu/Paddle#308]

**Comment by reyoung** [comment]
@20092136 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md#%E5%A5%BD%E9%97%AE%E9%A2%98%E4%B8%8E%E8%A0%A2%E9%97%AE%E9%A2%98
