### ISSUE TITLE
AttributeError: 'module' object has no attribute 'img_rnorm_layer' - while running image_classification demo training

### ISSUE THREAD

**Issue by deepcodingman** [baidu/Paddle#31]
I am trying to run image_classification demo but I am getting error during running train.sh (see log at the end).
I will appreciate your help in figuring out what is going wrong here.

- Mandeep

=============================================================
[17:54 ~/paddle/src/paddle/demo/image_classification] > ./train.sh
I0902 17:54:59.306221 16647 Util.cpp:144] commandline: /home/deepbeast/paddle/bin/bin/../opt/paddle/bin/paddle_trainer --config=vgg_16_cifar.py --dot_period=10 --log_period=100 --test_all_data_in_one_period=1 --use_gpu=1 --trainer_count=1 --num_passes=200 --save_dir=./cifar_vgg_model
I0902 17:55:04.945137 16647 Util.cpp:113] Calling runInitFunctions
I0902 17:55:04.945307 16647 Util.cpp:126] Call runInitFunctions done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3113, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3089, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "vgg_16_cifar.py", line 15, in <module>
    from paddle.trainer_config_helpers import *
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/__init__.py", line 19, in <module>
    from layers import *
AttributeError: 'module' object has no attribute 'img_rnorm_layer'
F0902 17:55:05.116209 16647 PythonUtil.cpp:130] Check failed: (ret) != nullptr Python Error: <type 'exceptions.AttributeError'> : 'module' object has no attribute 'img_rnorm_layer'
Python Callstack:
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3113
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3089
            vgg_16_cifar.py : 15
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/__init__.py : 19
Call Object failed.
*** Check failure stack trace: ***
    @     0x7fd2bd0f65cd  google::LogMessage::Fail()
    @     0x7fd2bd0f8433  google::LogMessage::SendToLog()
    @     0x7fd2bd0f615b  google::LogMessage::Flush()
    @     0x7fd2bd0f8e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x89fcb2  paddle::callPythonFuncRetPyObj()
    @           0x8a0176  paddle::callPythonFunc()
    @           0x6fb681  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x6fc99d  paddle::TrainerConfigHelper::createFromFlags()
    @           0x547dc4  main
    @     0x7fd2bc280830  __libc_start_main
    @           0x5501a9  _start
    @              (nil)  (unknown)
/home/deepbeast/paddle/bin/bin/paddle: line 46: 16647 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
No data to plot. Exiting!

**Comment by qingqing01** [comment]
You just need to remove `img_rnorm_layer` in line 39 in `python/paddle/trainer_config_helpers/layers.py`.  We have fixed it and will merge it soon.

**Comment by deepcodingman** [comment]
Thanks. that problem got resolved but now I am getting another error.

========
[18:40 ~/paddle/src/paddle/demo/image_classification] > ./train.sh
I0902 18:40:26.984419 27728 Util.cpp:144] commandline: /home/deepbeast/paddle/bin/bin/../opt/                                  paddle/bin/paddle_trainer --config=vgg_16_cifar.py --dot_period=10 --log_period=100 --test_al                                  l_data_in_one_period=1 --use_gpu=1 --trainer_count=1 --num_passes=200 --save_dir=./cifar_vgg_                                  model
I0902 18:40:29.325484 27728 Util.cpp:113] Calling runInitFunctions
I0902 18:40:29.325641 27728 Util.cpp:126] Call runInitFunctions done.
[INFO 2016-09-02 18:40:29,394 layers.py:1435] channels=3 size=3072
[INFO 2016-09-02 18:40:29,394 layers.py:1435] output size for __conv_0__ is 32
[INFO 2016-09-02 18:40:29,397 layers.py:1435] channels=64 size=65536
[INFO 2016-09-02 18:40:29,398 layers.py:1435] output size for __conv_1__ is 32
[INFO 2016-09-02 18:40:29,400 layers.py:1496] output size for __pool_0__ is 16*16
[INFO 2016-09-02 18:40:29,401 layers.py:1435] channels=64 size=16384
[INFO 2016-09-02 18:40:29,401 layers.py:1435] output size for __conv_2__ is 16
[INFO 2016-09-02 18:40:29,404 layers.py:1435] channels=128 size=32768
[INFO 2016-09-02 18:40:29,404 layers.py:1435] output size for __conv_3__ is 16
[INFO 2016-09-02 18:40:29,406 layers.py:1496] output size for __pool_1__ is 8*8
[INFO 2016-09-02 18:40:29,407 layers.py:1435] channels=128 size=8192
[INFO 2016-09-02 18:40:29,408 layers.py:1435] output size for __conv_4__ is 8
[INFO 2016-09-02 18:40:29,410 layers.py:1435] channels=256 size=16384
[INFO 2016-09-02 18:40:29,410 layers.py:1435] output size for __conv_5__ is 8
[INFO 2016-09-02 18:40:29,413 layers.py:1435] channels=256 size=16384
[INFO 2016-09-02 18:40:29,413 layers.py:1435] output size for __conv_6__ is 8
[INFO 2016-09-02 18:40:29,415 layers.py:1496] output size for __pool_2__ is 4*4
[INFO 2016-09-02 18:40:29,416 layers.py:1435] channels=256 size=4096
[INFO 2016-09-02 18:40:29,417 layers.py:1435] output size for __conv_7__ is 4
[INFO 2016-09-02 18:40:29,419 layers.py:1435] channels=512 size=8192
[INFO 2016-09-02 18:40:29,419 layers.py:1435] output size for __conv_8__ is 4
[INFO 2016-09-02 18:40:29,421 layers.py:1435] channels=512 size=8192
[INFO 2016-09-02 18:40:29,422 layers.py:1435] output size for __conv_9__ is 4
[INFO 2016-09-02 18:40:29,424 layers.py:1496] output size for __pool_3__ is 2*2
[INFO 2016-09-02 18:40:29,424 layers.py:1496] output size for __pool_4__ is 1*1
[INFO 2016-09-02 18:40:29,428 networks.py:1122] The input order is [image, label]
[INFO 2016-09-02 18:40:29,429 networks.py:1125] The output order is [__cost_0__]
I0902 18:40:29.442795 27728 Trainer.cpp:169] trainer mode: Normal
F0902 18:40:29.443608 27728 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0                                   vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***
    @     0x7feafca9f5cd  google::LogMessage::Fail()
    @     0x7feafcaa1433  google::LogMessage::SendToLog()
    @     0x7feafca9f15b  google::LogMessage::Flush()
    @     0x7feafcaa1e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x7ed69c  hl_gpu_apply_unary_op<>()
    @           0x7b3c3b  paddle::BaseMatrixT<>::applyUnary<>()
    @           0x7b37c5  paddle::BaseMatrixT<>::applyUnary<>()
    @           0x7952ec  paddle::BaseMatrixT<>::zero()
    @           0x65e3a0  paddle::Parameter::enableType()
    @           0x66e001  paddle::parameterInitNN()
    @           0x671ca5  paddle::NeuralNetwork::init()
    @           0x66797b  paddle::GradientMachine::create()
    @           0x6f1cfd  paddle::TrainerInternal::init()
    @           0x6eb38b  paddle::Trainer::init()
    @           0x547e65  main
    @     0x7feafbc29830  __libc_start_main
    @           0x5501a9  _start
    @              (nil)  (unknown)
/home/deepbeast/paddle/bin/bin/paddle: line 46: 27728 Aborted                 (core dumped) $                                  {DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
No data to plot. Exiting!

**Comment by emailweixu** [comment]
Can you provide your GPU card type and CUDA version? Thanks

**Comment by deepcodingman** [comment]
Please see below:

[19:08 ~] > lspci -nn | grep '\[03'
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1)
02:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1)


[19:08 ~] > cat  /usr/local/cuda/version.txt
CUDA Version 8.0.27
[19:08 ~] >

**Comment by gangliao** [comment]
Hi, invalid device function indicates that you have a CUDA / GPU incompatibility.
Since you use GTX 1080, you can modify CMake to fix it. 

1. open cmake/flags.cmake and  add following code:

`if (CUDA_VERSION VERSION_GREATER "8.0")`

`list(APPEND __arch_flags " -gencode arch=compute_60,code=sm_60")`

`endif()`

2. then, rebuild the project

**Comment by deepcodingman** [comment]
Now I am getting following error during running 'make -j all'

[ 16%] Built target paddle_utils
[ 16%] Building NVCC (Device) object paddle/gserver/CMakeFiles/paddle_gserver.dir/layers/paddle_gserver_generated_LstmCompute.cu.o
[ 19%] Built target paddle_pserver
[ 19%] Built target paddle_network
[ 19%] Building NVCC (Device) object paddle/gserver/CMakeFiles/paddle_gserver.dir/layers/paddle_gserver_generated_GruCompute.cu.o
[ 23%] Built target paddle_api
[ 26%] Built target paddle_trainer_lib
[ 31%] Built target paddle_parameter
/usr/local/cuda/include/surface_functions.h(134): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(135): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(136): error: expected a ";"

**Comment by gangliao** [comment]
Basically, we do not test PaddlePaddle on cuda 8.0. There maybe exist some incompatibility.
You can use `make clean; cmake ..; make VERBOSE=1` to figure out where the problem comes from.

**Comment by deepcodingman** [comment]
Thanks. I will give it a try again later once there is support for CUDA 8.0

**Comment by hedaoyuan** [comment]
CUDA 8.0 has support.
