### ISSUE TITLE
内存随Pass增加而增加，请owner看下cache清空机制是否存在问题

### ISSUE THREAD

**Issue by CDDB** [baidu/Paddle#311]
现象：
随着pass数目增加，内存增加（没10分钟一个pass）
![image](https://cloud.githubusercontent.com/assets/111802/19920074/8430114a-a111-11e6-85f9-46dfcfbc0806.png)

观察：
dataprovider很多时候推荐 CacheType.CACHE_PASS_IN_MEM，怀疑每轮pass都会吃下大量内存不清理。
快速过了下代码，观察到每个batch的操作：
`{
      PyGuard g;
      cache_->drop(&data);
    }`

但是，drop操作不清内存,droppedPool_也没有释放操作

验证：
采用 CacheType.NO_CACHE
![image](https://cloud.githubusercontent.com/assets/111802/19920531/37d633ee-a114-11e6-94a1-e0564e8bbe42.png)

**Comment by gangliao** [comment]
#310

**Comment by reyoung** [comment]
@CDDB Thank you for submitting this issue. It seems to be duplicated with issue #310.

I'm trying to figure out what's going on right now. Please tracking #310 for updates.
