### ISSUE TITLE
ImportError: No module named paddle.trainer.PyDataProvider2

### ISSUE THREAD

**Issue by ershersh** [baidu/Paddle#32]
First time to use paddle and not very familiar, so I try to do as the quickstart doc step by step.
http://www.paddlepaddle.org/doc/demo/quick_start/index_en.html
http://www.paddlepaddle.org/doc_cn/index.html
Environment: ubuntu 12.04 and install cpu-deb.
I have finished data preparation step and when i try to use dataprovider_bow.py script, it throw the error as my title,here is the log:

cloud@cloud-virtual-machine:~/paddle-git/demo/quick_start$ python dataprovider_bow.py 
Traceback (most recent call last):
  File "dataprovider_bow.py", line 15, in <module>
    from paddle.trainer.PyDataProvider2 import *
ImportError: No module named paddle.trainer.PyDataProvider2

What's the problem and how can i get that package imported correctly?? And i doubt if i install paddlepaddle correctly, how can i conform that??thx~

**Comment by gangliao** [comment]
Hi, @ershersh 

http://www.paddlepaddle.org/doc_cn/demo/quick_start/index.html
Most of python snippets in this page are to describe the details of our system how it works.
All python files in quick_start, including `dataprovider_bow.py` already in our script.
To make demo/quick_start runs, just typing following commands:
1. ./preprocess.sh
2. ./train.sh 
you can open and modify train.sh, choose different models to train data.
3. ./predict.sh

**Comment by stoneyang** [comment]
@ershersh 

It is an import issue of python librarary named `paddle.trainer.PyDataProvider2`.  
How did you build and install PaddlePaddle? If you didn't install it and python can't find a clue from the import commands in the script. As a fix, you may choose alternatives follows:

1. **Install PaddlePaddle**: after successfully executed `make` and install using `make install`, `sudo` may be necessary considering your local machines or consult your system administrator to properly install it. 

2. **Environment ablation**: just add the directory of PaddlePaddle's python utilities before you could run any py script:
```
export PYTHONPATH=/path/to/Paddle/python:$PYTHONPATH
```
or simply copy the above lines to your preprocess.sh.

P.S.: The link of PaddlePaddle's quick start in Chinese you provided in the original post is wrong and maybe you could fix it?

**Comment by ershersh** [comment]
First i have fix the link and add the English website. ^_^
@gangliao ./preprocess.sh run ok. and next I try this:
cloud@cloud-virtual-machine:~/paddle-git/demo/quick_start$ ./train.sh 
/usr/bin/../opt/paddle/bin/paddle_trainer: error while loading shared libraries: libprotobuf.so.8: cannot open shared object file: No such file or directory
it shows that error about that .so library... 

@stoneyang I use vmware11+ubuntu12.04 and install paddlepaddle by deb
root@cloud-virtual-machine:/home/cloud# dpkg -i paddle-0.8.0b0-Linux-cpu.deb 
Selecting previously unselected package paddle.
(正在读取数据库 ... 系统当前共安装有 147560 个文件和目录。)
正在解压缩 paddle (从 paddle-0.8.0b0-Linux-cpu.deb) ...
dpkg：依赖关系问题使得 paddle 的配置工作不能继续：
 paddle 依赖于 libatlas3-base；然而：
  未安装软件包 libatlas3-base。
 paddle 依赖于 libgflags2；然而：
  未安装软件包 libgflags2。
 paddle 依赖于 libgoogle-glog0；然而：
  未安装软件包 libgoogle-glog0。
 paddle 依赖于 libprotobuf8；然而：
  未安装软件包 libprotobuf8。
 paddle 依赖于 python-numpy；然而：
  未安装软件包 python-numpy。
 paddle 依赖于 python-pip；然而：
  未安装软件包 python-pip。
 paddle 依赖于 python-pip-whl；然而：
  未安装软件包 python-pip-whl。
dpkg：处理 paddle (--install)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 paddle
root@cloud-virtual-machine:/home/cloud# apt-get install -f
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
正在更正依赖关系... 完成
下列软件包将被【卸载】：
  paddle
升级了 0 个软件包，新安装了 0 个软件包，要卸载 1 个软件包，有 686 个软件包未被升级。
有 1 个软件包没有被完全安装或卸载。
解压缩后将会空出 320 MB 的空间。
您希望继续执行吗？[Y/n]n
中止执行。

After command dpkg -i paddle-0.8.0b0-Linux-cpu.deb ,it shows that i still have error--some dependences not install, the guide doc tell me then apt-get install -f will continue install paddle, and install dependences, but the fact is it try to remove paddle so i choose canceled.Maybe there's something wrong here??

So I may try @stoneyang your ways to install later , see whether it can fix and update the result in time.thx all

**Comment by NIULQfromNJU** [comment]
meybe you should enter the paddle/python dir and run "python setup.py install"

**Comment by ershersh** [comment]
@NIULQfromNJU i also try your method and did ont work
root@cloud-virtual-machine:/home/cloud/paddle-git/python# python setup.py.in install
Traceback (most recent call last):
  File "setup.py.in", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by stoneyang** [comment]
@ershersh 

From your rely, you installed PaddlePaddle on your virtual machine using [the shipped debian package](https://github.com/baidu/Paddle/releases/tag/V0.8.0b0) according to [the official instructions](www.paddlepaddle.org/doc/build/ubuntu_install.html). Since you try to install CPU version of PaddlePaddle, maybe you should pay attention to the Note about the instruction set of your CPU listed at the bottom of the instructions. And make sure you have the proper access permission. 

As a reminder, the two solutions I provided is about [building PaddlePaddle from the source code on your local machine](http://www.paddlepaddle.org/doc/build/build_from_source.html#build-and-install). You can try it out if needed.

**Comment by reyoung** [comment]
@ershersh You should use `apt-get update` before `apt-get install -f` to make `apt` can find dependencies.

**Comment by reyoung** [comment]
@ershersh Then you can follow the install instructions.

**Comment by ershersh** [comment]
@reyoung I also try your method but it comes to the same result:  after"apt-get install -f",it tells me to delete paddle. Now I use my spare time to install paddle by docker
thanks all the same!

**Comment by backyes** [comment]
more than 1 months passed, so close this issue.
