### ISSUE TITLE
集群训练如何打印测试集全局评估结果（如分类错误率等）？

### ISSUE THREAD

**Issue by sjtuwy** [baidu/Paddle#320]
> I1102 18:07:53.238729 23991 Tester.cpp:111]  Test samples=500000 cost=0.47127 Eval: macro-average-precision=0.786511 macro-average-recall=0.786473 macro-average-F1-score=0.786492 micro-average-precision=0.787206 classification_error_evaluator=0.212794 positive_label=0 precision=0.774611 recall=0.773681 F1-score=0.774146 positive_label=1 precision=0.798411 recall=0.799266 F1-score=0.798838 

集群训练，在paddle_trainer.INFO里只会打印测试集抽样的评估结果，请问打印测试集全局评估结果？

**Comment by backyes** [comment]
use --test_all_data_in_one_period, 
Refer:
http://www.paddlepaddle.org/doc/ui/cmd_argument/detail_introduction.html?highlight=test_all_data_in_one_period
