### ISSUE TITLE
初始化网络报错：Check failed: input.value The input of 'fc' layer must be matrix

### ISSUE THREAD

**Issue by 20092136** [baidu/Paddle#331]
I1102 20:25:50.893517 4574 Thread.h:209] SyncThreadPool worker thread 26 
I1102 20:25:50.893538 4575 Thread.h:209] SyncThreadPool worker thread 27 
I1102 20:25:50.893553 4576 Thread.h:209] SyncThreadPool worker thread 28 
I1102 20:25:50.893566 4577 Thread.h:209] SyncThreadPool worker thread 29 
I1102 20:25:50.893584 4578 Thread.h:209] SyncThreadPool worker thread 30 
I1102 20:25:50.893600 4579 Thread.h:209] SyncThreadPool worker thread 31 
F1102 20:25:57.201982 4124 FullyConnectedLayer.cpp:83] **Check failed: input.value The input of 'fc' layer must be matrix** 

这是我的网络配置
![image](https://cloud.githubusercontent.com/assets/1858392/19956940/8963c1dc-a1cc-11e6-95ae-9609237bc4e5.png)

dataprovider：
![image](https://cloud.githubusercontent.com/assets/1858392/19956857/9b1cf2be-a1cb-11e6-8d7e-cfa8dee73610.png)

**Comment by luotao1** [comment]
The 83 line of FullyConnectedLayer.cpp is :
```
auto input = getInput(i);
CHECK(input.value) << "The input of 'fc' layer must be matrix";
```
It means that input.value is nullptr. So check you data and dataprovider.

**Comment by 20092136** [comment]
![image](https://cloud.githubusercontent.com/assets/1858392/19957203/7d1093e4-a1cf-11e6-92b8-23fd9ab217aa.png)

看到train.log中有这么一条，意思是上一个 feat_slot（feat_slot: [4837, 439, 571, 6103, 6102, 6104] ）有问这样题么?这是个IndexSlot(6121)，这样也有错？
