### ISSUE TITLE
使用 SparseNonValueSlot 出错

### ISSUE THREAD

**Issue by 20092136** [baidu/Paddle#332]
使用 SparseNonValueSlot，yield 形如 [1,100,999] 的数据，出现错误

I1103 14:35:16.591063 29430 PythonUtil.cpp:83] Python Error: : 'int' object has no attribute '__getitem__' 
I1103 14:35:16.591128 29430 PythonUtil.cpp:87] Python Callstack: 
I1103 14:35:16.591142 29430 PythonUtil.cpp:92] /home/slurm/job/tmp/job-2825/paddle/trainer/PyDataProviderWrapper.py : 359 
I1103 14:35:16.591153 29430 PythonUtil.cpp:92] /home/slurm/job/tmp/job-2825/paddle/trainer/PyDataProviderWrapper.py : 525 
I1103 14:35:16.591163 29430 PythonUtil.cpp:92] /home/slurm/job/tmp/job-2825/paddle/trainer/PyDataProviderWrapper.py : 476 
F1103 14:35:16.591187 29430 PythonUtil.cpp:108] Call function getNextBatch failed. 

![image](https://cloud.githubusercontent.com/assets/1858392/19957652/78040076-a1d3-11e6-964d-beaff9b5a7d1.png)

对dataprovider的使用是否有问题？

**Comment by luotao1** [comment]
use_seq=True时，SparseNonValueSlot的格式是[[i, ...], [i, ...], ...]，参考http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html#input-types。（目前是sparse_binary_vector接口）

**Comment by 20092136** [comment]
如果我希望 IndexSlot 使用 seq，SparseNonValueSlot 不使用 seq，能够单独设置而不是通过use_seq来设置吗？

**Comment by luotao1** [comment]
可以的，不过得使用新接口，https://github.com/baidu/Paddle/blob/master/demo/sentiment/dataprovider.py 就使用了一个seq和一个非seq的IndexSlot。
