### ISSUE TITLE
Use original protostr for unittest of trainer_config_helper

### ISSUE THREAD

**Issue by emailweixu** [baidu/Paddle#342]
Currently, the unittest at python/paddle/trainer_config_helper/tests/configs/run_tests.sh compares the generated protostr with the desired protostr using md5sum. The problem is that once something is changed in a PR, it is very hard for the code reviewers to figure out the changes to the original protostr.

**Comment by luotao1** [comment]
如果github上的单测可以过，说明改过的protostr是没有问题的。

**Comment by reyoung** [comment]
We thought that to add the generated protostr into git is too noising, but it is very hard to code review. We should change them ASAP.

**Comment by reyoung** [comment]
@wen-bo-yang Could you help us to fix this issue? Just a good chance to learn `how to use git`, submit `PR`,  and Paddle unittest process.

**Comment by reyoung** [comment]
@wen-bo-yang 我说一下我们目前单测配置文件的一些上下文。

## Paddle配置文件解析

目前Paddle的配置文件通过在Python端一并序列化成 protobuf 的二进制格式，然后再交由C++端进行处理。配置文件的解析使用python，这样可以方便用户去配置网络格式，而不用手写繁杂的protostring

具体示意图如下\:
![image](https://cloud.githubusercontent.com/assets/728699/19993168/9399d256-a27e-11e6-8fa6-caf2c4d30a48.png)

## Paddle目前的配置文件单元测试

目前Paddle的配置文件单测在 [这里](https://github.com/baidu/Paddle/blob/develop/python/paddle/trainer_config_helpers/tests/configs/run_tests.sh)。它首先将这个目录的配置文件，转换成protostring文件，然后对比这个protostring文件的md5是否和原来记录的md5一致。

这样做就有一个问题是，我们在版本库里记录了md5值，而没有记录protostring应该是什么样子。导致我们写一个新的配置，或者修改了原来的配置，只能看到md5的变更，而看不到protostring的变更，这样不利于被code review。

## 这个issue想要更换的单测格式

我们想要先将每一个配置的protostr生成出来，然后保存到git版本管理中。

然后，再对比每一次单测时候，新生成的配置与在git中的配置是否一致即可。是否一致的对比我们还可以用md5来做。

比如，对于一个配置 `test_fc.py`。我们先用paddle生成一个配置文件 `test_fc.protostr`，保存在git中。在单测的时候，我们再生成一个文件 `test_fc.protostr.unittest`， 然后对比这两个文件的md5值一致即可。

整体的设计思路如上，请 @wen-bo-yang 确认一下

**Comment by wen-bo-yang** [comment]
@reyoung  明白，我先了解下整体流程。

**Comment by wen-bo-yang** [comment]
@reyoung  https://github.com/baidu/Paddle/pull/362
1. 增加了对当前配置文件的protostr文件，并保存与protostr文件夹下，该文件夹是新创建的。
如对test_fc.py生成的protostr文件名为test_fc.protostr，同时保存在porotsrt文件夹下。
2. 后续将生成的新的protostr文件保存在protostr下，并命名为xxx.protostr.unitest。
如对test_fc.py进行单侧是，会产生test_fc.protostr.unitest，并也将该文件保存在protostr文件夹下
3. 修改了check.md5 中第二列的，指定了生成unitest的路径和文件名。

**Comment by wen-bo-yang** [comment]
@reyoung https://github.com/baidu/Paddle/pull/363
1. 添加了新路径protostr用于保存以当前配置文件生成的protostr，同时将每次生成的protostr.unitest也保存在该路径下，路径名为：“Paddle/python/paddle/trainer_config_helpers/tests/configs/protostr”
如，test_fc.py 当前生成的protostr文件问test_fc.protostr，每次单侧生成的文件名问test_fc.protostr.unitest
2. 修改了check.md5文件第二列，检测生成文件的路径
3. 修改了generate_protostr.sh 将每次生成的protostr重新命名为xxx.protostr.unitest并保存在protostr路径下
