### ISSUE TITLE
Python unit test is using md5sum, a command doesn't come with Mac OS X

### ISSUE THREAD

**Issue by wangkuiyi** [baidu/Paddle#344]
https://github.com/baidu/Paddle/blob/develop/python/paddle/trainer_config_helpers/tests/configs/run_tests.sh invokes Linux command `md5sum`.  Mac OS X doesn't come with this command, but it has an equivalent tool `md5`.

**Comment by reyoung** [comment]
@wangkuiyi you can use `brew install md5sha1sum` to install this dependency.

**Comment by luotao1** [comment]
现在run_tests.sh用diff来直接比较protostr，已经不用md5sum命令了，见 #363
