### ISSUE TITLE
Check failed: size != 0  allocate 0 bytes

### ISSUE THREAD

**Issue by sjtuwy** [baidu/Paddle#350]
`I1104 11:56:41.373489 21424 ParameterServer2.cpp:255] pserver: setParameter
I1104 11:56:41.373515 21424 ParameterServer2.cpp:292] pserver: new cpuvector: size=0
F1104 11:56:41.373553 21424 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0 bytes`

集群训练，报上述错误，请帮忙排查？

**Comment by gangliao** [comment]
请粘贴详细的错误信息。@sjtuwy

**Comment by backyes** [comment]
@sjtuwy It could be caused by https://github.com/baidu/Paddle/pull/244, already fixed. 

You can try to upgrade Paddle.
