### ISSUE TITLE
Develop and deploy a GraphViz server, so to insert figures in Issues, PRs and documents.

### ISSUE THREAD

**Issue by wangkuiyi** [baidu/Paddle#351]

**Comment by reyoung** [comment]
@wangkuiyi http://www.gravizo.com/#samples is cool, but currently it cannot be used by issue.

**Comment by wangkuiyi** [comment]
That's alright. :-)  I am writing a *usable* server. Will submit for your review tomorrow.

**Comment by reyoung** [comment]
@wangkuiyi cool. But it seems that the github issue markdown has some errors yesterday. Today I am trying to use gravizo, is ok now. 

See 
![Alt text](http://g.gravizo.com/g?
  digraph G {
    A -> B
    B -> C
  }
)

```html
![Alt text](http://g.gravizo.com/g?
  digraph G {
    A -> B
    B -> C
  }
)
```

**Comment by wangkuiyi** [comment]
It might be a good idea to write our own gravizo and host it on paddlepaddle.org.

**Comment by reyoung** [comment]
Done.
![Alt text](http://api.paddlepaddle.org/graphviz?dot=https://gist.githubusercontent.com/wangkuiyi/c4e0015211dd1b9bde2e20455a6cd38e/raw/4d5ec099f98a5f326cf6f108bcf510cadba1a0b4/ci-arch.dot)
