### ISSUE TITLE
make error!

### ISSUE THREAD

**Issue by NIULQfromNJU** [baidu/Paddle#36]
[ 79%] Building CXX object paddle/utils/tests/CMakeFiles/test_CommandLineParser.dir/test_CommandLineParser.cpp.o
Linking CXX executable test_CommandLineParser
Done processing test_CommandLineParser.cpp
Total errors found: 0
/data10/anaconda2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_tmpnam':
/home/ilan/minonda/conda-bld/work/Python-2.7.12/./Modules/posixmodule.c:7631: warning: the use of `tmpnam_r' is dangerous, better use `mkstemp'
/data10/anaconda2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_tempnam':
/home/ilan/minonda/conda-bld/work/Python-2.7.12/./Modules/posixmodule.c:7578: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/data10/anaconda2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_forkpty':
posixmodule.c:(.text+0x2a8f): undefined reference to `forkpty'
/data10/anaconda2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_openpty':
posixmodule.c:(.text+0x4776): undefined reference to `openpty'
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/utils/tests/test_CommandLineParser] Error 1
make[1]: *** [paddle/utils/tests/CMakeFiles/test_CommandLineParser.dir/all] Error 2
make: *** [all] Error 2

**Comment by qingqing01** [comment]
Hi, @NIULQfromNJU 

I tested with anaconda2 python, when using the python lib `anaconda2/lib/python2.7/config/libpython2.7.a`, I have the same problem with you.

```
/home/xxx/anaconda2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_forkpty':
posixmodule.c:(.text+0x2a8f): undefined reference to `forkpty'
/home/xxx/anaconda2/lib/python2.7/config/libpython2.7.a(posixmodule.o): In function `posix_openpty':
posixmodule.c:(.text+0x4776): undefined reference to `openpty'
```

 But when using `anaconda2/lib/libpython2.7.so`, there is no problem. You can try it like:

```
cmake -DPYTHON_LIBRARY=/data10/anaconda2/lib/libpython2.7.so ..
```

**Comment by NIULQfromNJU** [comment]
Thanks @qingqing01 ~ I will try it later.
