### ISSUE TITLE
93e4d0cce 相对 45c81a414f  SgdSparseCpuTraining 慢了很多

### ISSUE THREAD

**Issue by linrongyi** [baidu/Paddle#366]
今天编译的时候checkout了最新的 93e4d0cce, 发现SgdSparseCpuTraining 速度相对 45c81a414f 慢了很多, 将近有10倍以上.

由于 @backyes 内部工具里面的mkl 工具没有  mkl_lapacke.h, 导致 93e4d0cce编译不过.  所以找了一个带有  mkl_lapacke.h 的MKL包. 两个版本都基于这个MKL编译的.

由于还没有修复GPU版本没有开启avx的功能, 所以编译的时候-DWITH_GPU=OFF.

**Comment by wangkuiyi** [comment]
@linrongyi 谢谢反馈这个问题。请问你是怎么测试SgdSparseCpuTraining的速度的？我们请paddle团队的同学也来复现一下这个问题，然后进一步找原因和解法。

**Comment by backyes** [comment]
@linrongyi 我们在确认https://github.com/baidu/Paddle/pull/359 的PR的意义。 这种10倍量级的性能差异极可能是使用上的问题，等我们确认mkl_lapacke.h的作用后再讨论解决方法。
@lzhao4ever 请知晓。
GPU avx BUG在 @hedaoyuan 的PR中https://github.com/baidu/Paddle/pull/239 中已经FIX， 该BUG比较紧急，请 @hedaoyuan 看看能否提供一个单独FIX的patch。

**Comment by emailweixu** [comment]
@backyes 在mkl里加上mkl_lapacke.h即可

**Comment by luotao1** [comment]
In `composer_xe_2013.0.079/mkl/include/mkl.h`, it includes mkl_lapack.h:
![mkl](https://cloud.githubusercontent.com/assets/6836917/20044521/9ae5fc4e-a4d4-11e6-97e1-6d9c0f69be6e.PNG)

**Comment by backyes** [comment]
@linrongyi 问题已经解决： 
* 性能问题。 根源是 @linrongyi 同学引用了一个性能存在问题的第三方MKL库
* mkl_lapacke.h引入的编译问题。已经通过添加『mkl_lapacke.h』头文件，解决。（我们提供的MKL缺少相关库头文件，不缺少函数实现）
