### ISSUE TITLE
python预测时CreateSparseMatrix出 core

### ISSUE THREAD

**Issue by 20092136** [baidu/Paddle#368]
以下是我使用 python 版本预测模块的方式：

```
from py_paddle import swig_paddle, DataProviderConverter
from paddle.trainer.PyDataProvider2 import *
from paddle.trainer.config_parser import *
                                        
def load_test_data():                   
    test_data = []                      
    with open('./test/sentiment/thirdparty/predictset.txt', 'r') as f:
        for line in f:                  
            arr = line.strip().split('\t')
            label = arr[0]              
            seq = arr[1].split()        
            feat = arr[2].split()       
            test_data.append([map(int, seq), map(int, feat), int(label)])
            print test_data             
            return test_data            
    return test_data                    
                                        
def main():                             
    swig_paddle.initPaddle("--use_gpu=0")                                    
    conf = parse_config("./model_output/pass-00000/trainer_config.py", "") 
    network = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)
    assert isinstance(network, swig_paddle.GradientMachine)  # For code hint.
    network.loadParameters("./model_output/pass-00000/")
                                        
    converter = DataProviderConverter([integer_value_sequence(319085),
        sparse_non_value_slot(6121), integer_value(888)])
    TEST_DATA = load_test_data()        
    inArg = converter.convert(TEST_DATA)
```

其中TEST_DATA的一个 sample 以及错误信息如下打印所示：

I1107 11:40:57.545857  2794 Util.cpp:144] commandline:  --use_gpu=0 
I1107 11:40:57.545934  2794 Util.cpp:113] Calling runInitFunctions
I1107 11:40:57.546272  2794 Util.cpp:126] Call runInitFunctions done.
[WARNING 2016-11-07 11:40:57,588 default_decorators.py:40] please use keyword arguments in paddle config.
[WARNING 2016-11-07 11:40:57,590 default_decorators.py:40] please use keyword arguments in paddle config.
[INFO 2016-11-07 11:40:57,595 networks.py:1122] The input order is [seq, feat]
[INFO 2016-11-07 11:40:57,595 networks.py:1129] The output order is [fc_ly_4]
I1107 11:40:57.912839  2794 GradientMachine.cpp:123] Loading parameters from ./model_output/pass-00000/
[[[290, 2201, 554, 37, 142, 237, 78, 60, 171, 1483, 1615, 2201, 229, 237, 50, 9, 18, 0, 2238, 204, 7, 2785, 15, 131, 2, 53, 79, 173, 52, 30, 345, 752, 110, 81, 690, 483, 2432, 2201, 19, 483, 1732, 125, 1483, 483, 55, 3909, 125, 1483, 86, 181, 695, 415, 14, 3, 22476, 370, 173, 242, 3], [494, 1333, 737, 3421, 1030, 6105], 206]]
F1107 11:40:57.991053  2794 CpuSparseMatrix.cpp:59] Check failed: newNnz <= newHeight * newWidth (6 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f3c8f1c8448  google::LogMessage::Fail()
    @     0x7f3c8f1c83a0  google::LogMessage::SendToLog()
    @     0x7f3c8f1c7e35  google::LogMessage::Flush()
    @     0x7f3c8f1cabf6  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3c8ede308a  paddle::CpuSparseMatrix::resize()
    @     0x7f3c8ede314f  paddle::CpuSparseMatrix::CpuSparseMatrix()
    @     0x7f3c8edf53ae  paddle::Matrix::createSparseMatrix()
    @     0x7f3c8ed6920e  Matrix::createSparse()
    @     0x7f3c8ed3bc8d  _wrap_Matrix_createSparse
    @           0x4b4cb9  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b6c52  PyEval_EvalCode
    @           0x4e1c7d  PyRun_FileExFlags
    @           0x4e3501  PyRun_SimpleFileExFlags
    @           0x4159dd  Py_Main
    @     0x7f3c92c9fbd5  __libc_start_main
    @           0x414b71  (unknown)
predict.sh: line 5:  2794 Aborted                 (core dumped) ./python27-gcc482/bin/python predict.py

追查 源码至py_paddle.dataprovider_converter.SparseBinaryScanner.finish_scan中创建 SparseMatrix出错，请问有可能是什么原因？

**Comment by hedaoyuan** [comment]
`Check failed: newNnz <= newHeight * newWidth (6 vs. 0)` 应该是finish_scan中createSparse时的参数有问题，你在SparseBinaryScanner.finish_scan中检查一下`self.__height__`和`self.input_type.dim`试试?

**Comment by 20092136** [comment]
这两个参数我都检查过，分别是0和6121

**Comment by reyoung** [comment]
> [INFO 2016-11-07 11:40:57,595 networks.py:1122] The input order is [seq, feat]
[INFO 2016-11-07 11:40:57,595 networks.py:1129] The output order is [fc_ly_4]

首先有另一个问题，你的网络只有两个输入，但是你的TEST_DATA给了三个。

**Comment by reyoung** [comment]
另外@20092136，您使用的Paddle版本是哪个？如果方便的话，请检查一下是不是这个版本之后的代码9f072c3613e2be3686afec9373b90059。之前的版本这块写的有些bug

**Comment by 20092136** [comment]
@reyoung 多谢指正 input 数量不对问题。
@reyoung 尝试用最新版本的 paddle 编译，执行预测脚本的时候出错在第一句
`from py_paddle import swig_paddle, DataProviderConverter`

错误信息：
Traceback (most recent call last):
  File "predict.py", line 15, in <module>
    from py_paddle import swig_paddle, DataProviderConverter
  File "/home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/util.py", line 19, in <module>
    import swig_paddle
  File "/home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: /home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: deflateInit2_

请问可能是什么问题？缺少什么依赖包吗？

**Comment by reyoung** [comment]
> ImportError: /home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: deflateInit2

看起来是编译错了。如果是百度内网用户的话，找一下王燕飞(@backyes)，他弄了一套二进制发行版。不需要编译了

**Comment by backyes** [comment]
@20092136 https://github.com/baidu/Paddle/pull/393 FIX了 ```mportError: /home/users/huangwenzhi/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: deflateInit2``` ，请更新到主干代码
