### ISSUE TITLE
【Transfer Data to Model】模板下的【Python Use Case】连接丢失

### ISSUE THREAD

**Issue by beckett1124** [baidu/Paddle#387]
在快速入门文档中 ，查看数据传送模型中用例参考文档Python Use Case时，找不到对应的页面。

![python_case](https://cloud.githubusercontent.com/assets/12882811/20084734/487b0b36-a59f-11e6-9214-b60fb92be8a3.png)

查看paddle的github的code中没有看到对应python_case的文件。
![f383106de5dd2f7463a73be9b](https://cloud.githubusercontent.com/assets/12882811/20084842/f7ef7cfa-a59f-11e6-88a7-1c78a6d5f669.png)

**Comment by reyoung** [comment]
@qingqing01 麻烦看一下，这个文档似乎有些deadlink。麻烦看一下。

另外，我们应该弄一个文档扫描deadline的工具。

**Comment by reyoung** [comment]
Closed by PR #389
