### ISSUE TITLE
MAC OS X下执行preprocess.sh找不到对应的shuf命令

### ISSUE THREAD

**Issue by beckett1124** [baidu/Paddle#388]
在MAC OS X下执行preporcess.sh预处理数据，找不到对应的shuf命令，手动安装shuf的基库coreutils：brew install coreutils，依然找不到对应的shuf命令。
经查证MAC下的shuffle的shell命令是gshuf，执行which gshuf找到gshuf确实存在，路径为/usr/local/bin/gshuf。
而preporcess.sh 针对数据的随机排序采用的命令是shuf，修改脚本中shuf为gshuf命令。

**Comment by reyoung** [comment]
恩，这个我们会看一下。在preprocess.sh里面处理一下操作系统的问题。
