### ISSUE TITLE
running error!

### ISSUE THREAD

**Issue by NIULQfromNJU** [baidu/Paddle#39]
When i run the quick_start, i have the following error:
paddle_trainer: error while loading shared libraries: libgflags.so.2: cannot open shared object file: No such file or directory
But i have installed gflags.2.2.0, which includes the following libs:
/usr/local/lib/libgflags.so      /usr/local/lib/libgflags.so.2.2.0      /usr/local/lib/libgflags_nothreads.so.2.2
/usr/local/lib/libgflags.so.2.2  /usr/local/lib/libgflags_nothreads.so  /usr/local/lib/libgflags_nothreads.so.2.2.0

why paddle use libgflags.so.2 instead of libgflags2.2.0???

Besides, when i installed gflags2.0, which includes libgflags.so.2, but i also have another running error:
paddle: line 46:  1877 Illegal instruction     ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

why?

**Comment by hedaoyuan** [comment]
libgflags.so.2 is a symbolic link of libgflags.so.2.2.0.
The reason for paddle use libgflags.so.2 instead of libgflags2.2.0, is libgflags2.1.0 is also ok.
You can add  a symbolic link of libgflags, like this: ln -s libgflags.so.2.1.0 libgflags.so.2

**Comment by NIULQfromNJU** [comment]
Thanks @hedaoyuan 
I reinstall gflags using gflags-2.1.2 ( [https://github.com/gflags/gflags/releases] ) and these exists libgflags.so,2.
But when i run quick_start demo, i have the another error like this:
/paddle: line 46: 14445 Illegal instruction     ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by emailweixu** [comment]
Make sure your cpu support avx instructions. Otherwise you need to compile PaddlePaddle with WITh_AVX turning off for cmake

**Comment by NIULQfromNJU** [comment]
Thanks @emailweixu . The reason is my CPU do not support avx instructions, after turning WITH_AVX OFF, paddle run successfully.
