### ISSUE TITLE
MAC OS 系统下执行demo的训练，提示：ImportError: No module named _swig_paddle

### ISSUE THREAD

**Issue by beckett1124** [baidu/Paddle#396]
在mac os系统下，执行paddle自带的demo，模型训练失败。
具体错误如下：

qibinMacBook-Pro:quick_start baidu$ sh api_train.sh 
py_paddle
Traceback (most recent call last):
  File "api_train.py", line 20, in <module>
    from py_paddle import swig_paddle as api
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/util.py", line 19, in <module>
    import swig_paddle
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 22, in <module>
    _swig_paddle = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 21, in swig_import_helper
    return importlib.import_module('_swig_paddle')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _swig_paddle

注：已通过port更新MAC OS下的gcc版本为gcc4.8

**Comment by gangliao** [comment]
@beckett1124  swig装了吗？

**Comment by gangliao** [comment]
目前我们把mac build doc删除了，等完整测试后才会再次放开。如果你严格安装https://github.com/baidu/Paddle/commit/2e1d968fc284fa733e6ed20191875b003116c083这个流程编译， 安装，paddle是能够正常运行的。

**Comment by beckett1124** [comment]
swig 是正确安装的。
![image](https://cloud.githubusercontent.com/assets/12882811/20091804/b0f0ba14-a5cf-11e6-9691-d6fb21bd567f.png)

**Comment by gangliao** [comment]
@beckett1124  安装下面的流程 重新试一次 谢谢
```
cmake .. -DWITH_SWIG_PY=ON -DCMAKE_INSTALL_PREFIX=<installation path>
sudo make install
sudo pip install <path to install>/opt/paddle/share/wheels/*.whl
sudo paddle version
```

**Comment by XanderXu** [comment]
@beckett1124 怎么解决的?求助...

**Comment by yanmengqi** [comment]
我也出现了这个问题

**Comment by XanderXu** [comment]
@yanmengqi 我解决了.用`install_name_tool -change`替换成自己的python就行.  

第一步:用otool -L命令来检查_swig_paddle.so文件的依赖关系.你会发现有个路径不存在
`/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)`这个不存在.
```
otool -L /Users/我的名字/Library/Python/2.7/lib/python/site-packages/py_paddle/_swig_paddle.so
```

第二步:用`install_name_tool -change 参数一 参数二 参数三`完成替换.
参数一是旧路径(不存在的路径):`/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python`,
参数二是自己的python路径,我用的是系统自带的版本:`/System/Library/Frameworks/Python.framework/Versions/2.7/Python`,
参数三是实际的paddle文件路径:`/Users/我的名字/Library/Python/2.7/lib/python/site-packages/py_paddle/_swig_paddle.so`
完整命令如下:
```
sudo install_name_tool -change /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python 
/System/Library/Frameworks/Python.framework/Versions/2.7/Python   
/Users/我的名字/Library/Python/2.7/lib/python/site-packages/py_paddle/_swig_paddle.so
```
第三步:可以再用`otool -L /Users/我的名字/Library/Python/2.7/lib/python/site-packages/py_paddle/_swig_paddle.so`检查一遍是否成功
