### ISSUE TITLE
Matrix.cpp:2769] Check failed: label.getSize() == numSamples (13 vs. 127) 

### ISSUE THREAD

**Issue by 13488862011** [baidu/Paddle#397]
使用demo里的semantic_role_labeling 做训练时，出现以下的错；训练目标对时序的序列进行预测
sh train.sh
Tue Nov  8 16:31:54 CST 2016
I1108 16:31:54.986636 10316 Util.cpp:144] commandline: /home/liupeng07/.jumbo/bin/../opt/paddle/bin/paddle_trainer --config=./zj_lstm.py --save_dir=./output --trainer_count=11 --log_period=10 --num_passes=200 --use_gpu=false --show_parameter_stats_period=10 --test_all_data_in_one_period=1 
I1108 16:31:54.986928 10316 Util.cpp:113] Calling runInitFunctions
I1108 16:31:54.987305 10316 Util.cpp:126] Call runInitFunctions done.
[INFO 2016-11-08 16:31:58,187 networks.py:1122] The input order is [word_data, target]
[INFO 2016-11-08 16:31:58,187 networks.py:1129] The output order is [__cost_0__]
I1108 16:31:59.038832 10316 Trainer.cpp:169] trainer mode: Normal
I1108 16:32:01.214412 10316 PyDataProvider2.cpp:219] loading dataprovider zj_dataprovider::process
I1108 16:32:01.696892 10316 PyDataProvider2.cpp:219] loading dataprovider zj_dataprovider::process
I1108 16:32:01.697199 10316 GradientMachine.cpp:134] Initing parameters..
I1108 16:32:11.124802 10316 GradientMachine.cpp:141] Init parameters done.
I1108 16:32:11.483523 10524 ThreadLocal.cpp:39] thread use undeterministic rand seed:10525
I1108 16:32:11.543462 10521 ThreadLocal.cpp:39] thread use undeterministic rand seed:10522
I1108 16:32:11.554527 10515 ThreadLocal.cpp:39] thread use undeterministic rand seed:10516
I1108 16:32:11.556932 10518 ThreadLocal.cpp:39] thread use undeterministic rand seed:10519
I1108 16:32:11.560775 10517 ThreadLocal.cpp:39] thread use undeterministic rand seed:10518
I1108 16:32:11.564555 10519 ThreadLocal.cpp:39] thread use undeterministic rand seed:10520
I1108 16:32:11.566588 10520 ThreadLocal.cpp:39] thread use undeterministic rand seed:10521
I1108 16:32:11.566684 10523 ThreadLocal.cpp:39] thread use undeterministic rand seed:10524
I1108 16:32:11.567601 10516 ThreadLocal.cpp:39] thread use undeterministic rand seed:10517
I1108 16:32:11.574527 10525 ThreadLocal.cpp:39] thread use undeterministic rand seed:10526
I1108 16:32:11.577190 10522 ThreadLocal.cpp:39] thread use undeterministic rand seed:10523
F1108 16:32:12.580016 10517 Matrix.cpp:2769] Check failed: label.getSize() == numSamples (13 vs. 127) 
*** Check failure stack trace: ***
    @     0x7f627ecd1a6d  google::LogMessage::Fail()
    @     0x7f627ecd5f07  google::LogMessage::SendToLog()
    @     0x7f627ecd3d69  google::LogMessage::Flush()
    @     0x7f627ecd406d  google::LogMessageFatal::~LogMessageFatal()
    @           0x7de658  paddle::CpuMatrix::oneHotCrossEntropy()
    @           0x66b7ed  paddle::CostLayer::forward()
    @           0x5d1c36  paddle::NeuralNetwork::forward()
    @           0x5b2db3  paddle::TrainerThread::forward()
    @           0x5b423c  paddle::TrainerThread::computeThread()
    @     0x7f627e81d2a8  execute_native_thread_routine
    @     0x7f627f6d2d14  start_thread
    @     0x7f627dfdabfd  clone

**Comment by zhangjcqq** [comment]
貌似是数据的问题，看看13和127是否是对应着数据的某个信息，比如词典、目标label集合的大小，某个句子的长度？还有，每次报错的时候，是否每次都是这两个值？

**Comment by 13488862011** [comment]
报错的时候，13和127不是固定的，比如会是14和138；词典是162675维，目标label集合是171666；训练数据是：
f1 f2 f3 f4 f5 f6 f7 f8 f9  \t  l1
................
f1 f2 f3 f4 f5 f6 f7 f8 f9   \t  l171666

**Comment by zhangjcqq** [comment]
这种数据格式并不是SRL demo中处理完的数据格式，自己处理的？做的是SRL任务吗？看上去像是文本分类之类的事情。14和138应该是句子长度相关的一些值，建议使用一个只有一句或几句话的小训练数据来调试，这样每次报错的时候，值会是固定的，容易发现问题。

**Comment by 13488862011** [comment]
是的 是自己处理的，目标是根据已知的序列，预测下一个可能得序列

**Comment by zhangjcqq** [comment]
你的任务非常像language model任务，实际上是个序列分类问题，而不是sequence labeling的问题。建议参考情感分析的demo，https://github.com/baidu/Paddle/tree/develop/demo/sentiment

**Comment by 13488862011** [comment]
sequence labeling 最多支持多少个label的分类？

**Comment by zhangjcqq** [comment]
具体多少个label没测过，应该是可以满足大部分应用需求。
sequence labeling问题的定义就是给序列中的每个单元分类，所以输入和输出长度是一样的。

**Comment by 13488862011** [comment]
好的 3q
序列的预测是不是用seq2seq 也可以？

**Comment by zhangjcqq** [comment]
可以尝试。

**Comment by reyoung** [comment]
@zhangjcqq 这个issue解决了么？解决了可以close

**Comment by 13488862011** [comment]
多谢 已经解决了
