### ISSUE TITLE
ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by fc500110** [baidu/Paddle#405]
I1109 12:57:20.163054 2054201344 Util.cpp:130] Calling runInitFunctions
I1109 12:57:20.163236 2054201344 Util.cpp:143] Call runInitFunctions done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 87, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/usr/local/lib/python2.7/site-packages/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
  File "/usr/local/lib/python2.7/site-packages/paddle/proto/TrainerConfig_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
F1109 12:57:20.254937 2054201344 PythonUtil.cpp:191] Check failed: (module) != nullptr Current PYTHONPATH: ['/usr/local/paddle/opt/paddle/bin', '/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg', '/usr/local/lib/python2.7/site-packages', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-darwin', '/usr/lib/python2.7/plat-mac', '/usr/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/Extras/lib/python', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages']
Python Error: <type 'exceptions.ImportError'> : No module named google.protobuf
Python Callstack:
            /usr/local/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 87
            /usr/local/lib/python2.7/site-packages/paddle/proto/__init__.py : 15
            /usr/local/lib/python2.7/site-packages/paddle/proto/TrainerConfig_pb2.py : 6
Import paddle.trainer.config_parserError
*** Check failure stack trace: ***
    @        0x1078339da  google::LogMessage::Fail()
    @        0x1078330d5  google::LogMessage::SendToLog()
    @        0x10783363b  google::LogMessage::Flush()
    @        0x107836a17  google::LogMessageFatal::~LogMessageFatal()
    @        0x107833cc7  google::LogMessageFatal::~LogMessageFatal()
    @        0x1066ceed9  paddle::py::import()
    @        0x1066ce96c  paddle::callPythonFuncRetPyObj()
    @        0x1066cf4f6  paddle::callPythonFunc()
    @        0x1065d212b  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @        0x1065d33a0  paddle::TrainerConfigHelper::createFromFlags()
    @        0x1064c3c94  main
    @     0x7fff9ab345ad  start
    @                0x9  (unknown)
/usr/local/paddle/bin/paddle: line 81: 12798 Abort trap: 6           ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
编译成功，运行的时候出错，自己写程序import这些module是没问题的

**Comment by wangkuiyi** [comment]
Can you try `sudo pip install protobuf`?

**Comment by fc500110** [comment]
@wangkuiyi 
安装了，import google.protobuf是没问题的，我是在mac上编译安装的

**Comment by fc500110** [comment]
@wangkuiyi 
感觉是不是因为多个Python的问题？

**Comment by backyes** [comment]
@fc500110 另外请明确下：
* 你是在什么平台上安装的paddle
* 如何安装的paddle？ 是源码安装么？

你可以排查：
* 是否安装了多个python解释器版本

如果没猜错的话，是因为操作系统环境下有多个python解释器版本，触发cmake find python的bug所致，参看：https://github.com/baidu/Paddle/pull/328

**Comment by fc500110** [comment]
@backyes 
我是在mac上装的paddle，源码编译安装，这是我的编译选项 cmake .. -DWITH_SWIG_PY=ON -DWITH_DOC_CN=ON -DWITH_GPU=OFF -DWITH_DOC=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/paddle -DOPENBLAS_ROOT=/usr/local/openblas/
编译没有问题

**Comment by backyes** [comment]
@wangkuiyi 和 @backyes 都怀疑是您的系统里有多个python解释器，请确认下这个先。

**Comment by reyoung** [comment]
@fc500110 你的系统里可能使用了多个python解释器，导致pip安装的包不在paddle实际的解释器中。

请使用virtualenv，并在进入virtualenv后，再运行paddle。

**Comment by backyes** [comment]
主要问题集中在系统多个python版本，且长时间无响应，close issue。
