### ISSUE TITLE
集群训练错误：Import paddle.trainer.config_parserERROR

### ISSUE THREAD

**Issue by Lionyan** [baidu/Paddle#425]
步骤：
1. 使用『一键安装』在三台CentOS6.3的机器上分别安装成功paddle，并且尝试单机模式运行demo/recommendation的例子：成功运行
2.尝试其中一台机器作为主机，另外的2台机器作为节点尝试集群训练：
2.1 主机上copy demo/recommendation下所有文件到/home/paddle/root下
2.2 主机上copy paddle/scripts/cluster_train/ 下三个脚本到/home/paddle/root下
2.3 修改/home/paddle/root/conf.py: 
HOSTS = [
        "root@<ip of node1>",
        "root@<ip of node2>",
        ]
ROOT_DIR = "/home/paddle/root"

除了这两个其他的都没有修改

2.4 三台机器都运行pip install fabric

3. 主机上在/home/paddle/root目录下运行sh run
4. 查看node节点下的log:

train.log:
/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
F1110 16:10:30.047618 29776 PythonUtil.cpp:191] Check failed: (module) != nullptr Current PYTHONPATH: ['/home/paddle/paddle_internal_release_tools/idl/paddle/output/opt/paddle/bin', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/paddle/root/JOB20161110161019', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python27.zip', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/plat-linux2', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-tk', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-old', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-dynload', '/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages']
Python Error: <type 'exceptions.ImportError'> : No module named trainer.config_parser
Python Callstack:
Import paddle.trainer.config_parserError
*** Check failure stack trace: ***
    @          0x13a2218  google::LogMessage::Fail()
    @          0x13a2170  google::LogMessage::SendToLog()
    @          0x13a1c05  google::LogMessage::Flush()
    @          0x13a49c6  google::LogMessageFatal::~LogMessageFatal()
    @           0x808742  paddle::py::import()
    @           0x8087fc  paddle::callPythonFuncRetPyObj()
    @           0x808bf1  paddle::callPythonFunc()
    @           0x6fde2e  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x6fe48d  paddle::TrainerConfigHelper::createFromFlags()
    @           0x58c77c  main
    @     0x7f12b6c33bd5  __libc_start_main
    @           0x597d85  (unknown)
/home/paddle/paddle_internal_release_tools/idl/paddle/output/bin/paddle: line 81: 29776 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

server.log:
F1110 16:10:24.771934 28292 LightNetwork.cpp:68] Check failed: ioctl(sock, 0x8915, &ifr) >= 0 (-1 vs. 0)
*** Check failure stack trace: ***
    @          0x1361288  google::LogMessage::Fail()
    @          0x13611e0  google::LogMessage::SendToLog()
    @          0x1360c75  google::LogMessage::Flush()
    @          0x1363a36  google::LogMessageFatal::~LogMessageFatal()
    @           0x6dd2aa  paddle::getIpAddr()
    @           0x57bcaf  main
    @     0x7f684d97bbd5  __libc_start_main
    @           0x586579  (unknown)
/home/paddle/paddle_internal_release_tools/idl/paddle/output/bin/paddle: line 81: 28292 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_pserver_main ${@:2}

求帮助！

**Comment by backyes** [comment]
@Lionyan 应该属于环境变量问题导致， 内部用户一键脚本编译的paddle主要为单机用户，多机用户请走平台化。
具体错误原因大致如下：
* fabirc默认ssh构建的进程环境变量，不支持读取~/.bashrc, 不支持搜索非系统默认路径。
* 一键安装通过控制~/.bashrc，达到修改当前shell解释器环境变量，并最终构造出paddle运行时环境，包括python、paddle相关二进制等。故 用fabirc实现的开源多机脚本，不支持这种用法。

技术上，如果非要用开源集群脚本私自搭建paddle集群，可以考虑hack paddle.py将一键脚本安装的几个环境变量设置增加到fabric构建的ssh shell环境中，具体可以参看：config.py中对cuda环境变量的设置。另外，也可以通过fabric相关组建，达到相关目的。 核心就是修改进程环境变量，是的进程内python能搜索到私有的python库。

**Comment by backyes** [comment]
@Lionyan ，
@reyoung 发现你的错误可能是因为使用了版本不匹配的demo程序： 
```
No module named trainer.config_parser
```
请使用跟你编译使用的Paddle一致的demo代码，再跑集群试试。

**Comment by Lionyan** [comment]
@backyes，
 我使用的demo所有 脚本都是同一次下载下来的代码库里的，应该不存在不一致的问题，这个库找不到的确很费解：因为它就存在在/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages里，作为一个workaround,我把/home/paddle/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle 拷贝到$(ROOT_DIR)里，这个错误（No module named trainer.config_parser）就没有了。

但是log里另外一个错误还存在：

cat train.log
[INFO 2016-11-10 18:56:29,481 networks.py:1282] The input order is [movie_id, title, genres, user_id, gender, age, occupation, rating]
[INFO 2016-11-10 18:56:29,481 networks.py:1289] The output order is [__regression_cost_0__]
F1110 18:56:30.050752 22706 LightNetwork.cpp:379] Check failed: connect(sockfd, (sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR connecting to 10.89.140.14: Connection refused [111]
*** Check failure stack trace: ***
    @           0x70f6e0  paddle::SocketClient::TcpClient()
    @           0x70f821  paddle::SocketClient::SocketClient()
    @           0xf55320  paddle::ParameterClient2::init()
    @           0x706bed  paddle::RemoteParameterUpdater::init()
    @           0x6f0c9b  paddle::Trainer::init()
    @           0x58c831  main
    @     0x7f4845b20bd5  __libc_start_main
    @           0x597d85  (unknown)
/home/paddle/paddle_internal_release_tools/idl/paddle/output/bin/paddle: line 81: 22706 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

# cat server.log
F1110 18:56:24.059141 21259 LightNetwork.cpp:68] Check failed: ioctl(sock, 0x8915, &ifr) >= 0 (-1 vs. 0)
*** Check failure stack trace: ***
    @           0x6dd2aa  paddle::getIpAddr()
    @           0x57bcaf  main
    @     0x7f3c9cf09bd5  __libc_start_main
    @           0x586579  (unknown)
/home/paddle/paddle_internal_release_tools/idl/paddle/output/bin/paddle: line 81: 21259 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_pserver_main ${@:2}

这个log所在的节点是10.89.140.15,但却尝试链接另外一个节点10.89.140.14

**Comment by backyes** [comment]
@Lionyan 内部用户考虑用平台化，即可。开源集群脚本，默认在docker安装环境下使用，你目前的使用场景暂时不支持。

**Comment by Lionyan** [comment]
@backyes 我们产品针对的客户是外部的客户，而且是需要将paddle部署在外面的，不知道这方面有什么的约束？比如操作系统？比如只能单机不能集群？

我们本来在CentOS6.3上尝试手动编译安装，但是错误太多，无法解决，所以才想到先用一键安装，再弄明白其中原理再想办法移植到外部，安装的问题暂时用一键安装解决了，但是现在又遇到了集群训练的问题......

**Comment by backyes** [comment]
@Lionyan 你的问题非常好，同时也非常抱歉给你带来困扰，我们会持续不断改善文档，让用户不再对此类问题感到疑问。
解答如下：
* Paddle目前只有对外开源一版，且维护在github
* 内部用户将通过一键编译工具、jumbo、平台化等，满足对单机训练、大规模多机训练需求，其中
     * 一键编译和jumbo主要为了满足单机用户的快速调研，后续将逐渐deprecate jumbo安装，取代为一键安装。另外，一键安装通过submodule的方式引用开源github库，满足内部用户需求。
     * 多机训练默认都是基于Paddle平台化，支持对接公司内部MPI计算集群。
* 普通开源社区用户，可以通过多机脚本 paddle.py 工具满足对多机训练的需求

所以，你尝试通过开源多机脚本paddle.py搭建私有paddle集群进行多机训练也是可行的，但是仍然建议您利用内部平台化进行多机训练。

**Comment by Lionyan** [comment]
@backyes Connect refused 的问题是因为网卡类型参数设置不对，已解决

**Comment by jayhenry** [comment]
原因是没有指定参数 `--nics=eth0`

- 这个报错真是太 confusing了，用户完全不知道什么原因
- 默认参数指定eth0可以省去debug很多时间
- 教程很多地方都是没有指定nics参数的用法，比如 http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/cluster/cluster_train_cn.html

希望在以上地方改进 @backyes
