### ISSUE TITLE
将sentiment分类demo中的lstmemory换成simple_lstm后发现训练速度变慢，并且cost值下降也很慢

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#426]
使用sentiment分类demo中的三层LSTM，demo中原始使用的是lstmemory，在[文档](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers.html?highlight=lstmemory)中发现lstmemory需要配上fc_layer才是完整的lstm layer，于是我替换成了simple_lstm进行尝试，结果发现训练速度变得非常慢，并且cost值变化也很慢。

如图，注释掉的是原始demo中的lstmemory，红框部分是我改写的simple_lstm，并且发现使用simple_lstm后内存为7.4g(lstmemory内存仅为3.8g)：
![image](https://cloud.githubusercontent.com/assets/4569055/20172042/6a710c9c-a76e-11e6-868a-1829031833af.png)

以下是simple_lstm训练日志：
![image](https://cloud.githubusercontent.com/assets/4569055/20172509/4d8f7c1a-a770-11e6-9fd2-5dee108f8edb.png)
以下是lstmemory训练日志：
![image](https://cloud.githubusercontent.com/assets/4569055/20172573/9f342444-a770-11e6-8327-90655bbaa968.png)

**Comment by qingqing01** [comment]
@333caowei 

-  首先更改前后连接不等价，demo提供的连接图是 http://www.paddlepaddle.org/doc/demo/sentiment_analysis/sentiment_analysis.html#stacked-lstm ，参考paper http://www.aclweb.org/anthology/P/P15/P15-1109.pdf 
   这和你改之后的连接不等价的。

- 内存会涨、速度会慢是因为 `simple_lstm`中： https://github.com/baidu/Paddle/blob/develop/python/paddle/trainer_config_helpers/networks.py#L488
这里的fully-connected的size是`4 * hid_dim`。而改之前的`fc_layer`的size是`hid_dim`。

**Comment by 333caowei** [comment]
@qingqing01 如果是使用标准的lstm的话，以下三种，哪种正确呢

第一种：    ouput = simple_lstm(input=input, size=hid_dim, act=relu)

第二种：    ouput = lstmemory(input=input, act=relu)

第三种：    fc       = fc_layer(input=input, size=hid_dim, act=linear)
                  ouput = lstmemory(input=fc, act=relu)

**Comment by qingqing01** [comment]
第一种正确~

**Comment by 333caowei** [comment]
@qingqing01 非常感谢
