### ISSUE TITLE
阡陌机器一键安装paddle,提示缺少fatal error: glog/logging.h: No such file or directory

### ISSUE THREAD

**Issue by beckett1124** [baidu/Paddle#427]
阡陌机器一键安装paddle，提示fatal error: glog/logging.h: No such file or directory。

具体情况如下：
Scanning dependencies of target paddle_utils
[ 13%] Building CXX object paddle/utils/CMakeFiles/paddle_utils.dir/Excepts.cpp.o
Done processing src/hl_time.cc
Total errors found: 0
[ 14%] Building CXX object paddle/utils/CMakeFiles/paddle_utils.dir/Version.cpp.o
Done processing include/hl_activation_functions.h
Total errors found: 0
In file included from /home/paddle/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/Util.h:31:0,
                 from /home/paddle/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/Version.cpp:19:
/home/paddle/paddle_internal_release_tools/idl/paddle/Paddle/paddle/utils/Logging.h:183:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
                          ^
compilation terminated.
make[2]: *** [paddle/utils/CMakeFiles/paddle_utils.dir/Version.cpp.o] Error 1
make[1]: *** [paddle/utils/CMakeFiles/paddle_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Done processing include/hl_aggregate.h
Total errors found: 0

**Comment by backyes** [comment]
内部使用问题。
