### ISSUE TITLE
按照quick start运行出错

### ISSUE THREAD

**Issue by LooJee** [baidu/Paddle#43]
您好，我按照你们的quick start配置好了环境，运行train.sh的时候报了错误：
`/usr/local/bin/paddle: line 46:  4977 Illegal instruction     (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}`

**Comment by LooJee** [comment]
我用的是ubuntu14.04的虚拟机。不知道和指令集有没有关系，我先把本地支持的指令集放上来：
`flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer xsave rdrand hypervisor lahf_lm abm arat epb pln pts dtherm fsgsbase tsc_adjust invpcid xsaveopt
`

**Comment by NIULQfromNJU** [comment]
我之前也遇到过 不支持AVX。CMAKE时关闭WITH_AVX

**Comment by LooJee** [comment]
谢谢，确实是因为不支持AVX的原因，在 cmake 的时候加上 -DWITH_AVX=OFF 就行了。
