### ISSUE TITLE
trainer_count=4, 但是top命令显示paddle进程占用为99%

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#432]
训练参数中设定trainer_count=4,但是通过top命令发现paddle的cpu占有率依然是99%，似乎并没有多线程：
![image](https://cloud.githubusercontent.com/assets/4569055/20203410/056ab912-a802-11e6-961a-68612f36bd67.png)
![image](https://cloud.githubusercontent.com/assets/4569055/20203429/26e44df6-a802-11e6-9f4e-63b4282af231.png)

**Comment by backyes** [comment]
@reyoung 你知道是什么原因么？ 实际一般我都不看这个数据，而是看多核各个核的时间计算占有率，这个99%意义不大，可能跟我司hack内核有关。

**Comment by backyes** [comment]
@333caowei 这个疑问可以找内核组同学确认。

**Comment by reyoung** [comment]
paddle使用单线程异步读取训练数据。如果batchsize过小，训练数据读取速度赶不上计算速度，那么很可能性能热点会在读数据上。

并且，paddle会在pass开始之前预读一部分数据。在这时候很可能是单线程的。开始计算后才会占用对应资源。


发自 Smartisan T2

backyes <notifications@github.com> 于 2016年11月11日，上午11:57写道：


@333caowei<https://github.com/333caowei> 这个疑问可以找内核组同学确认。

―

**Comment by hedaoyuan** [comment]
`但是通过top命令发现paddle的cpu占有率依然是99%` 用`top -H`可以查看每个线程的情况。

**Comment by 333caowei** [comment]
使用htop命令后看见了paddle每个线程的工作情况详情，多线程正常。
