### ISSUE TITLE
Design doc for paddle on spark

### ISSUE THREAD

**Issue by hohdiy** [baidu/Paddle#439]
为paddle on spark进行宣传，参看https://github.com/hohdiy/paddle_on_spark/blob/master/doc/paddle_on_spark.md

**Comment by wangkuiyi** [comment]
没看明白这个issue的上下文。

看到一个链接，指向一个repo，里面只有两个.md文档。为什么需要PR这个repo呢？

**Comment by luotao1** [comment]
@hohdiy md文档中paddle的网络配置，采用的是以前老版本的配置方式，目前已采用新接口。请参考 http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers_index.html

**Comment by hohdiy** [comment]
好的，新接口的样例，我这边会更新上去，并把其更新到我们的项目中。

**Comment by wangkuiyi** [comment]
和这个issue的作者线下沟通了一下，更新情况并周知：

1. 感谢 @hohdiy 的热情工作，努力将Paddle在Spark平台上运行起来。
1. 大家赞同这个项目在一个独立的Github repo里运营，而不是作为 Paddle repo 的一个子目录。
1. 如果 Paddle on Spark 项目需要Paddle团队的帮助，欢迎将Paddle团队的成员加入到 Paddle on Spark 项目中作为 collaborators。这样 Paddle on Spark 项目中的 PR 和 issue 可以被assign 给 Paddle 项目的成员，Github会给大家发邮件提醒，以便发起讨论。
1. 如果 Paddle on Spark 项目进行过程中有关于 Paddle 的问题，请在这里（Paddle repo）里提出。Paddle 团队来帮助解决。

多谢 @hohdiy ！
