### ISSUE TITLE
lstmemory这个layer的输出是什么样子？

### ISSUE THREAD

**Issue by tj554121946** [baidu/Paddle#451]
看了代码没有看的太懂，所以想问问lstmemory这个layer的输出是什么？我理解的是，根据公式，在某个时间t，lstm的输出就是一个浮点数，其维度为1没错吧？然后输入一个时间序列x的话，输出的就是一个1维的时间序列y，通过maxpooling之后得到的就是得到的就是max(y)，也只有1维，就是一个浮点数，请问有理解错吗？

**Comment by pengli09** [comment]
您的理解是不对的，公式里的输入、输出都是向量表示，并不是单个数，此类写法在deep learning相关论文中是比较普遍的。相应的，lstmemory在每个时间步t的输出是一个向量，而非一个数。

**Comment by tj554121946** [comment]
@pengli09 谢谢您的回答，我刚刚看了一下lstm的公式http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers.html#lstmemory
最后的输出是三个点乘加上一个偏置之后经过一个激活函数。为什么这样的输出会是一个向量呢，可否解答一下，谢谢。

**Comment by pengli09** [comment]
公式里的x_t是向量，不是一个数，W_*都是矩阵。这种向量化的符号表示参见http://ufldl.stanford.edu/wiki/index.php/%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C 中的例子
