### ISSUE TITLE
关于本地gpu mode下sparse更新

### ISSUE THREAD

**Issue by hiahiahu** [baidu/Paddle#456]
本地训练 use_gpu=1, 然后某一层设置sparse_update
![image](https://cloud.githubusercontent.com/assets/21326658/20254710/eb63837e-aa71-11e6-8703-3003ec6ac55f.png)
训练时候显示trainer_mode 为sparseCPU，麻烦问下这样是不是没用上GPU
![image](https://cloud.githubusercontent.com/assets/21326658/20254734/17056a56-aa72-11e6-8ccb-13ed744d944c.png)

或者这种情况有什么方法能最大限度的提高训练速度?谢谢

**Comment by backyes** [comment]
@hedaoyuan  @qingqing01  有空能帮忙看下？

**Comment by hedaoyuan** [comment]
`麻烦问下这样是不是没用上GPU`这个可以用`nvidia-smi`看一下GPU有没有工作。
`SgdSparseCpuTraining`好像只是gradient update的时候是CPU的计算。
`或者这种情况有什么方法能最大限度的提高训练速度?` `sparse_update`本来就是为了提高性能用的。

**Comment by hiahiahu** [comment]
@hedaoyuan 
这个可以用nvidia-smi看一下GPU有没有工作 =》如果当前gupid上还跑着其他gpu任务时 显存占用增多是不是就在gpu训练,；为什么我重新设置use_gpu=0(还开着sparse_update=1) 训练速度差不多没什么变化，会不会是因为我模型太简单，GPU加速对比CPU不明显？
SgdSparseCpuTraining好像只是gradient update的时候是CPU的计算=》是不是说gpu只有在前向的时候才有效，gradient update没法gpu计算(不懂gpu。。。)

谢谢！

**Comment by hedaoyuan** [comment]
` 显存占用增多是不是就在gpu训练` 是的，使用GPU训练的话，`parameter`, `argument`都是在GPU显存上配分的。
`会不会是因为我模型太简单` ，贴一下你的模型看看？
另外，启动后的log信息也可以多贴一些。

**Comment by hiahiahu** [comment]
模型很简单 直接两个seq分别过embedding，average之后接一层fc 然后求cos_sim
`opt/paddle/bin/paddle_trainer --use_gpu=1 --config=ps_bow_cos.conf --save_dir=./output_sum1 --num_passes=20000 --saving_period=1 --dot_period=100000 --log_period=100 --show_parameter_stats_period=100 --load_missing_parameter_strategy=rand --local=1 --use_old_updater=1 --test_period=100 --test_all_data_in_one_period=1 --average_test_period=10000000 --gpu_id=2 --saving_period_by_batches=4000 --trainer_count=2
I1114 16:31:08.678453  8877 Util.cpp:113] Calling runInitFunctions
I1114 16:31:08.678915  8877 Util.cpp:126] Call runInitFunctions done.
I1114 16:31:08.914249  8877 Trainer.cpp:121] ignore sparse_remote_update=true due to  --local=true
I1114 16:31:08.914288  8877 Trainer.cpp:166] trainer mode: SgdSparseCpuTraining
I1114 16:31:08.914604  8877 MultiGradientMachine.cpp:108] numLogicalDevices=1 numThreads=2 numDevices=4
I1114 16:31:08.952708  8877 PythonUtil.cpp:147] createPythonClass moduleName.c_str:dataprovider_gz
I1114 16:31:08.952725  8877 PythonUtil.cpp:152] createPythonClass className.c_str():processData
I1114 16:31:09.682157  8877 PythonUtil.cpp:147] createPythonClass moduleName.c_str:dataprovider_gz_copy_1
I1114 16:31:09.682190  8877 PythonUtil.cpp:152] createPythonClass className.c_str():processData_test
I1114 16:31:10.416023  8877 GradientMachine.cpp:134] Initing parameters..
I1114 16:31:27.513639  8877 GradientMachine.cpp:141] Init parameters done.
`

SgdSparseCpuTraining好像只是gradient update的时候是CPU的计算 =》gpu不能做反向么？还是gpu反向没有sparseCPU快，

**Comment by hedaoyuan** [comment]
`--use_gpu=1`时forward和backward（计算梯度）都是GPU计算的，`gradient update`仅仅只的是梯度更新。

**Comment by hiahiahu** [comment]
谢谢！懂啦
