### ISSUE TITLE
ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#460]
执行predict任务，当`from py_paddle import swig_paddle, DataProviderConverter`时候报错：

`ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/nuomi/.jumbo/lib/python2.7/site-packages/py_paddle/_swig_paddle.so)`

请问这个需要怎么解决呢，paddle是源码编译安装的，谢谢

**Comment by backyes** [comment]
你的问题根源是， swig_paddle的编译运行时环境和运行时的机器运行时环境不一致导致的。 

一般建议检查： 
* 编译Paddle时候，采用的编译器版本？
* 确保运行环境和编译环境一致。

如果要获取更多帮助， 建议提供以下内容：
* 你如何编译paddle的？ 请确保采用某一种特定的编译方法，不要混用

**Comment by 333caowei** [comment]
@backyes 
现在paddle训练没问题，只是predict时候会报错。
paddle安装过程如下：

```
export PATH=/opt/compiler/gcc-4.8.2/bin/:$PATH
cd baidu/idl/paddle/paddle/internals/scripts/build_scripts/
bash install_deps.jumbo.sh

```
```
cd ../../../..
cmake -DCMAKE_INSTALL_PREFIX="~/software/paddle" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCUDNN_ROOT="${JUMBO_ROOT}/opt/cudnn/" -DMKL_ROOT="${HOME}/downloads/baidu/idl/paddle/paddle/internals/mkl/" -DWITH_SWIG_PY=ON
make
```

```
echo "export LD_LIBRARY_PATH=$HOME/.jumbo/opt/cudnn/lib64:\$LD_LIBRARY_PATH" >> "$HOME/.bash_profile"
source ~/.bash_profile
make test
make install
```

**Comment by backyes** [comment]
问题应该是： 

* 从```/home/nuomi/.jumbo/lib/python2.7/site-packages/p``` 判断，你用的python解释器是jumbo python，它应该不是用gcc48编译出来的，即其和gcc48 运行时环境不兼容
* 从```export PATH=/opt/compiler/gcc-4.8.2/bin/:$PATH``` 判断，你编译paddle和py_paddle用的是gcc48环境，运行也将依赖该48运行时环境
因此，非48运行时环境依赖的 python27 加载gcc48运行时环境依赖的py_paddle的时候出现上述不兼容问题。 

解决方法两个： 
* 找一个gcc 48的编译出来的python解释器，并记得确保新python解释器成功替换到默认解释器。这个可以从paddle 一键编译脚本的 thirdparty中（免费:-)）获取.
* 全部用一键编译工具，它会自动处理上述所有依赖。比如，它运行时，不依赖系统python环境解释器。详细参看一键编译文档。
