### ISSUE TITLE
Unknown CMake command "add_style_check_target".

### ISSUE THREAD

**Issue by VamWolf** [baidu/Paddle#461]
CMake Error at cuda/CMakeLists.txt:84 (add_style_check_target):
  Unknown CMake command "add_style_check_target".

-- Configuring incomplete, errors occurred!

**Comment by backyes** [comment]
@VamWolf  add_style_check_target is defined in Paddle/cmake/cpplint.cmake. 

Could you show us more details? How to reproduce your issue?

**Comment by reyoung** [comment]
You compile paddle in wrong directory!

The root CMakeLists.txt is in git clone directory.

Please `git clone Paddle; cd Paddle`, not `git clone Paddle, cd Paddle/paddle`

**Comment by backyes** [comment]
no response for long time, so close it.
