### ISSUE TITLE
Paddle使用求助：预测模型

### ISSUE THREAD

**Issue by liuzongquan** [baidu/Paddle#465]
大咖们，
我在使用paddle解决一个预测模型时遇到一些，期望得到大家的帮助和回复，先谢谢大家了。
我的问题是这样的：
train.dat如下
col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,label
0.6004053786,0.955187599926,2,3,0.991455200062,0.508602067761,0.088945346,0.044968775,0.3596
0.6004053786,0.955187599926,1,1,0.991455200062,0.508602067761,0.06316632,0.023484437,0.1584
0.6004053786,0.955187599926,2,3,0.991455200062,0.508602067761,0.087739105,0.044656454,0.2072
......

由于不确定输入的feature跟label之间的关系到底是什么样的，所以决定选用神经网络跑一下看看。训练数据集很大，大概有上亿条记录。
我在使用paddle的时候，打算创建一个三层的神经网络，输入层->全连接隐层(使用fc_layer)->输出层，然后使用regression_cost()计算误差，最后输出模型。

我的问题是，从fc_layer到输出之间的这个层我不确定应该使用什么？
我看了paddle.org/doc中所有页面，还是没能找到一个合适的layer将一个number list映射到一个number。所以期望得到大家的帮助和指导，再次感谢！

**Comment by zhouxiao-coder** [comment]
不知道我有没有理解错你的问题，你是想说：如何从你图上的 col1 - col8 的输入得到最后的 1维 output score？

如果是的话，答案也非常简单：只要把最后输出层的宽度设为1即可。 这里有一个[简单的例子](https://github.com/baidu/Paddle/blob/develop/doc_cn/introduction/index.md) 供参考。

针对你的例子来讲，就像这样：
```
output_layer = fc_layer(input=hidden##你的隐层##, param_attr=ParamAttr(name='w'), size=1, act=LinearActivation(), bias_attr=ParamAttr(name='b'))
cost = regression_cost(input=output_layer, label=y##目标label##)
outputs(cost)
```

**Comment by liuzongquan** [comment]
赞！是的，这正是我想要的~ 非常感谢！
