### ISSUE TITLE
CMake Error shows the version wrong

### ISSUE THREAD

**Issue by gaoshan2006** [baidu/Paddle#467]
I installed gflags from source code. And gflags was built in /home/local/. Then when I compiled Paddle, I was meeting the following errors.  I have verified the CMake version on my machine is 3.6 above 2.8,  however it always shows "This file relies on consumers using CMake 2.8.12 or greater.", What's the reason ? Could you help me please ? Thanks

/////////////////////////////////////////////////////////////////////////////////////////////////////////
cmake  .. -DWITH_GPU=OFF -DWITH_DOC=OFF

-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
CMake Error at /home/local/lib/cmake/gflags/gflags-targets.cmake:66 (message):
  This file relies on consumers using CMake 2.8.12 or greater.
Call Stack (most recent call first):
  /home/local/lib/cmake/gflags/gflags-config.cmake:10 (include)
  cmake/FindGflags.cmake:318 (find_package)
  CMakeLists.txt:27 (find_package)
////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by hedaoyuan** [comment]
Have not encountered such a problem. 
Try modify the first line of the `CMakeLists.txt` file to `cmake_minimum_required (VERSION 2.8.12)`.
By the way, what version of `gflags` you use?

**Comment by gaoshan2006** [comment]
The version of  gflags source code I got from github  is 1.8.3.1
I modified CMakeLists.txt file, by changing  "cmake_minimum_required (VERSION 2.8) " to "cmake_minimum_required (VERSION 2.8.12) "

Then the error shows: 
cmake .. -DWITH_GPU=OFF -DWITH_DOC=OFF
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 2.8.12 or higher is required.  You are running version 2.8.11

But actually, when I check cmake version ("cmake -version"), the result is :
cmake version 3.6.20160704-g75232

**Comment by hedaoyuan** [comment]
I think the problem may be in your cmake environment.
In my environment, `cmake -version` show `cmake version 3.2.2`.
If set `cmake_minimum_required(VERSION 3.3)`,  the following error will be reported.
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>  CMake 3.3 or higher is required.  You are running version 3.2.2
If set the VERSION less than 3.2, no error reported.

**Comment by gaoshan2006** [comment]
Make sense.  It looks the problem is from my cmake.  Thanks a lot !
