### ISSUE TITLE
Whether forwardTest is thread safety or not while using python predict module?

### ISSUE THREAD

**Issue by 20092136** [baidu/Paddle#469]

**Comment by backyes** [comment]
这个 @reyoung 解释下吧，涉及到py_paddle实现细节。

**Comment by reyoung** [comment]
No, it is not thread safe. Also use multithread in Python is a very bad practice because of PIL.

**Comment by backyes** [comment]
@20092136 既然不是线程安全的，如果必须考虑多核加速的话，其实可以考虑多进程。

@reyoung py_paddle 支持MulitiGradientMachine驾驭多核多gpu么？
