### ISSUE TITLE
py_paddle-0.8.0b2-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by VamWolf** [baidu/Paddle#470]
py_paddle-0.8.0b2-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

安装过程，各种正常，直到运行，出这个错误.  怎么解决？

**Comment by reyoung** [comment]
https://github.com/baidu/Paddle/blob/develop/doc_cn/faq/index.rst#cp27mu-linux-x86-64-whl-is-not-a-supported-wheel-on-this-platform
