### ISSUE TITLE
paddle一键编译删除后如何清理python环境配置

### ISSUE THREAD

**Issue by DrakeNi** [baidu/Paddle#475]
RT, 基于paddle百度内部一键编译 的脚本安装后，现在删除paddle后，python的PYTHONHOME 和 PYTHONPATH变量无法清理干净，python无法使用，请教清除依赖的方法

**Comment by backyes** [comment]
@DrakeNi 

* 删除 ~/.bashrc 中几个paddle相关环境变量，然后re-login ssh

即可恢复原始环境变量。
