### ISSUE TITLE
Check failed: (size_t)lbl[i] < dim (69729 vs. 69729) 

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#477]
训练过程中报如下错误，不知是什么原因，（69729是当前分类任务的label数目）

![image](https://cloud.githubusercontent.com/assets/4569055/20296918/86b72494-ab48-11e6-91ab-c9335ac5b0b7.png)

**Comment by reyoung** [comment]
Paddle的Label从0开始计数，比如十分类问题的话，label是0-9

**Comment by 333caowei** [comment]
@reyoung 非常感谢，问题解决了
