### ISSUE TITLE
Do we need to keep one PYTHON repo. for easy cluster deployment, easy installation, easy compilation?

### ISSUE THREAD

**Issue by backyes** [baidu/Paddle#480]
* Paddle集群作业需要私有的python解释器。因为集群环境复杂多样，依赖系统自带的python不够现实，所以一般都是集群job都是自带一个python解释器
* 单机用户也面临python问题。单机用户在编译、安装阶段中，python相关问题也非常严重。https://github.com/baidu/Paddle/issues/297 是其中一个问题。
* 集群用户在跑不同作业时，比如image classification、nlp等，可能需要多种python库，但是普通用户在解决此类问题时，非常头疼，尤其在集群环境下。
* Paddle本身依赖c++11语法，为此需要高版本编译器，为此所依赖的python解释器也需要做到高版本编译，否则潜在的有不兼容风险，比如某些python库采用so动态库实现。因此，高版本运行时环境依赖的python，在安装其他python库的时候，也可能因为某些so不是包版本编译的，导致很多运行时问题。例如，pip install x.lib,  如果x.lib依赖低版本的运行时库，那么通过pip安装的python库，是无法运行到paddle进程空间内的。

综上，如果我们最好维护一个专门服务Paddle的python解释器，持续不断升级更新，满足多种场景下的需求。（目前我们私自维护了一个python解释器，相对封闭，贡献的人少，遇到问题需要专人处理，转么维护一个repo，可以多人贡献、分享）

讨论：

* 默认gcc48编译器编译
* 是否要升级python到更高版本，比如3.x版本

@reyoung @wangkuiyi @qingqing01 @luotao1 @hedaoyuan @gangliao 有什么邮件。

**Comment by reyoung** [comment]
如果是百度外部使用的话，docker可以做这些所有事情，并不需要特殊维护任何东西。

如果是百度内部使用的话，我们可以帮着编译一套python，事实上我去年干过。编译完的python可以自行使用pip安装各类python包。所以，也只需要分发二进制就可以了。

另外python是开源软件，如果我们对其有修改或者维护，必须按照它的license来。

最后，python3和这事情没有关系，可以查下issue我之前回答过python3为啥不支持。

**Comment by backyes** [comment]
> 如果是百度内部使用的话，我们可以帮着编译一套python，事实上我去年干过。编译完的python可以自行使用pip安装各类python包。所以，也只需要分发二进制就可以了。

这里存在一个运行时环境问题，有些库pip安装上来是不能run的，需要单独维护跟python运行时环境一致的python库。

> Paddle本身依赖c++11语法，为此需要高版本编译器，为此所依赖的python解释器也需要做到高版本编译，否则潜在的有不兼容风险，比如某些python库采用so动态库实现。因此，高版本运行时环境依赖的python，在安装其他python库的时候，也可能因为某些so不是包版本编译的，导致很多运行时问题。例如，pip install x.lib, 如果x.lib依赖低版本的运行时库，那么通过pip安装的python库，是无法运行到paddle进程空间内的。

**Comment by backyes** [comment]
@reyoung 相关问题 https://github.com/baidu/Paddle/issues/472

**Comment by reyoung** [comment]
pip是可用的。

我看@backyes主要觉得pip不可用是因为害怕pip安装python包的时候，使用了一个和python，paddle都不太一样的编译器。导致运行时有一些问题。

这个担心按照我的理解应该是不必要的。因为pip可以选择编译器呀。我们可以在pip运行之前，先将编译器切换到paddle使用的编译器上。

所以，对于百度内部来说，在集群运行脚本中，加一个requirements.txt，在运行集群训练的时候，现场装用户需要的python库就行了。


发自 Smartisan T2

backyes <notifications@github.com> 于 2016年11月16日，上午9:56写道：


如果是百度内部使用的话，我们可以帮着编译一套python，事实上我去年干过。编译完的python可以自行使用pip安装各类python包。所以，也只需要分发二进制就可以了。

这里存在一个运行时环境问题，有些库pip安装上来是不能run的，需要单独维护跟python运行时环境一致的python库。

Paddle本身依赖c++11语法，为此需要高版本编译器，为此所依赖的python解释器也需要做到高版本编译，否则潜在的有不兼容风险，比如某些python库采用so动态库实现。因此，高版本运行时环境依赖的python，在安装其他python库的时候，也可能因为某些so不是包版本编译的，导致很多运行时问题。例如，pip install x.lib, 如果x.lib依赖低版本的运行时库，那么通过pip安装的python库，是无法运行到paddle进程空间内的。

―

**Comment by backyes** [comment]
@reyoung 

> 因为pip可以选择编译器呀

这个靠谱么？ 如果靠谱，能解决大部分问题了。我们也可以实验一下。

**Comment by backyes** [comment]
> 这个担心按照我的理解应该是不必要的。因为pip可以选择编译器呀。我们可以在pip运行之前，先将编译器切换到paddle使用的编译器上。
@reyoung 我线下测试了一下，确认pip一般安装wheel包的时候是不源码编译的，比如numpy、pillow都是安装pip源对应的so版本，所以选择编译器也解决不了这些问题。但是实测发现，numpy和pillow自带的so库并不影响使用，import导入成功。长期角度来看，应该还是存在风险，但是短期内问题不大。感谢你的建议。

另外，这个问题我再继续线下维护一个python版本，给集群和内部单机一键编译使用。这里先close

**Comment by reyoung** [comment]
如果想用源码的话，直接pip那个源码包就行了。。仔细看下numpy的二进制后缀，是manylinux，即似乎只依赖了非常低版本的libc。pip可以安装二进制的时候，一般那个二进制就是可以被大多数发行版使用的。
