### ISSUE TITLE
quick_start执行preprocess.sh时，preporcess关于shuf的处理对于Ubuntu 14.04.5系统，得到的shuf为gshuf

### ISSUE THREAD

**Issue by beckett1124** [baidu/Paddle#487]
概述：
         quick_start执行preprocess.sh时，preporcess.sh关于shuf的处理对于Ubuntu 14.04.5系统，得到的shuf为gshuf。
      if的的问题导致。

    
![image](https://cloud.githubusercontent.com/assets/12882811/20343501/87395dce-ac29-11e6-8a6f-45b6778e5aad.png)

**Comment by gangliao** [comment]
@beckett1124 Ok, I will fix it. Thanks

**Comment by gangliao** [comment]
@beckett1124  Fixed it in PR #488
