### ISSUE TITLE
Paddle/demo/recommendation的数据预处理python依赖第三方库

### ISSUE THREAD

**Issue by DrakeNi** [baidu/Paddle#489]
RT, 使用一键编译版本，处理demo的推荐，数据预处理依赖
requirements.txt
由于是开发机，无法通过pip联网安装，而 jumbo的python无法安装docopt 和PyYAML

一键编译的版本也无法处理，求解决办法

**Comment by backyes** [comment]
此问题跟Paddle无直接关系。

内网同学可以通过咨询内部途径解决。
