### ISSUE TITLE
Is it possible to change the optimizer after N no. of steps? 

### ISSUE THREAD

**Issue by alvations** [baidu/Paddle#494]
For example, I want to take 500 batches with ADAM and then afterwards change to SGD where each epoch has around 10,000 batches. Is there a way to do it with `paddle train`? 

Or can I only change the optimizer after a pass is finished and I stop the training manually and re-run `paddle train` with the new settings?

**Comment by qingqing01** [comment]
> can I only change the optimizer after a pass is finished and I stop the training manually and re-run paddle train with the new settings?
This is a viable way.

**Comment by alvations** [comment]
One related question, how can I use the plain SGD in Paddle? The [`BaseSGDOptimizer`](https://github.com/baidu/Paddle/blob/develop/python/paddle/trainer_config_helpers/optimizers.py#L40) throws `NotImplementedError`.

**Comment by reyoung** [comment]
> Or can I only change the optimizer after a pass is finished and I stop the training manually and re-run paddle train with the new settings?

This way is currently recommended way, however, the python trainer is under writing. You can use python to control whole train process when python trainer is done. Now it is lack of documentation and lots of features. https://github.com/baidu/Paddle/blob/develop/demo/quick_start/api_train.py

The plain SGD in Paddle is MomentumOptimizer, where `momentum` set to `0.0`.

**Comment by alvations** [comment]
Thanks @qingqing01 @reyoung! I'll take a look at the `api_train.py` and see whether I can help to contribute =)

**Comment by reyoung** [comment]
@alvations Actually, we are not figure out what should we add to Python/MultiLanguage API yet. It is cool if you want to tell us what you need or what you want to control during train process.
Related Issue #258

**Comment by backyes** [comment]
@alvations 
Before the new feature you wanted is ready, I think, you can use ``--init_model_path``` to re-train model with new algorithm, right?  But the method  may cause some accuracy loss.

**Comment by alvations** [comment]
`--init_model_path` does something else right? 

Does it makes sense to write something like this in `optimizers.py`:

```python
class PlainSGDOptimizer(MomentumOptimizer):
    def __init__(self):
        super().init(momentum=0)
```

**Comment by reyoung** [comment]
> Before the new feature you wanted is ready, I think, you can use --init_model_path` to re-train model with new algorithm, right? But the method may cause some accuracy loss.

`--init_model_path` should help @alvations, but there is no accuracy loss.

To change the optimizer, the high order parameter of gradient should be reset to zero, such as momentum, or the other parameters in optimizer.

**Comment by reyoung** [comment]
> Does it makes sense to write something like this in optimizers.py:

It is welcome to write this optimizer, and please don't forget write the api comments with RST format. It will help us to generate api documentation like [this](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/optimizers.html#momentumoptimizer).

Please use the latest code in develop branch when contribute it, because we change the python code a lot by format code style. It will be hard to merge if you use older code.

**Comment by alvations** [comment]
Thanks @reyoung @backyes! I'll try to run the code with the SGD patching before doing a PR =) I'll also take a look at `--init_model_path` as well as #258 .

**Comment by backyes** [comment]
> --init_model_path should help @alvations, but there is no accuracy loss.

Yes,  that @reyoung said is right.   I was gonna say that with ```--init_model_path``` method Paddle can not utilize the  some SGD temporary information before previous passes. But that's not useful for you scene, since you will select other sgd optimizer, which can not use previous SGD history.
