### ISSUE TITLE
sentiment demo中的分类标签数是不是有问题

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#496]
在情感分类数据集中的标签是0、1，也就是,2个label，但是在demo代码中如图：

![image](https://cloud.githubusercontent.com/assets/4569055/20374745/a1c46eea-acb5-11e6-82de-c6608a8e9136.png)

label的size是1，应该是2才对吧？

**Comment by qingqing01** [comment]
@333caowei  这里配置成1或者2都是可以的，label是integer_value类型，这个size实际在程序中没有用到。
