### ISSUE TITLE
settings.slots和settings.input_types的区别

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#497]
在dataprovider2[文档](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html?highlight=pydataprovider2)中使用settings.input_types将数据喂给模型使用，但是在[这里](http://www.paddlepaddle.org/doc/algorithm/rnn/rnn.html?highlight=settings%20slots)使用的是settings.slots，不知这两个有什么区别

**Comment by luotao1** [comment]
rnn的这个文档还未更新，谢谢您的指正！

**Comment by reyoung** [comment]
> 在dataprovider2文档中使用settings.input_types将数据喂给模型使用，但是在这里使用的是settings.slots，不知这两个有什么区别

他们是同一个变量，只是我们一开始使用的input_slots的概念来写代码。 `slot`是最开始的code name，但是我们觉得`input_types`这个名字可以让用户更容易理解，所以将slots改名成了input_types。但是之前的slots由于向后兼容的要求，仍然保留。
