### ISSUE TITLE
paddle_trainer failed kill paddle_pserver2 and exit

### ISSUE THREAD

**Issue by 333caowei** [baidu/Paddle#498]
训练过程中出现如下错误，不知是何原因：

![image](https://cloud.githubusercontent.com/assets/4569055/20375974/d6eb0540-acbd-11e6-865b-4a655de71692.png)

**Comment by backyes** [comment]
参考： https://github.com/baidu/Paddle/issues/56 

I  search keywords  with```github paddle sigfp``` with google search engine, then find issue related above, so also recommend you to do it.
