### ISSUE TITLE
【文档】【demo情感分析】在介绍aclImdb中的train和test时，两路径中的文件并不是完全一样，文档介绍会产生歧义

### ISSUE THREAD

**Issue by wen-bo-yang** [baidu/Paddle#501]
在介绍aclImdb中的train和test两个数据集路径时，文档中说这两个路径下的所包含的文件是一样的，但实际对比后是不同的。用户会对此产生疑惑，是否我的程序有问题。
![image](https://cloud.githubusercontent.com/assets/6229206/20378491/78eb84e2-acd1-11e6-84d8-8b04149f102e.png)
实际路径下的文件
![image](https://cloud.githubusercontent.com/assets/6229206/20378505/88d65d46-acd1-11e6-8a9f-910194f7a001.png)

**Comment by luotao1** [comment]
感谢您的指出，我们会修改文档！
