### ISSUE TITLE
【文档】【demo情感分析】在trainer_config.py代码事例中，对于Algorithm Configuration的解释，是否能给出对应的在实例中的明确代码，对于普通用户来说，可能并不知道在哪里设置了average sgd window

### ISSUE THREAD

**Issue by wen-bo-yang** [baidu/Paddle#503]
在trainer_config.py代码事例中，对于Algorithm Configuration的解释，是否能给出对应的在实例中的明确代码，对于普通用户来说，可能并不知道在哪里设置了average sgd window，文档中只给出了setting中做了什么事情。
![image](https://cloud.githubusercontent.com/assets/6229206/20378720/c7a2bb54-acd2-11e6-8ed1-d0118cbe3092.png)

**Comment by luotao1** [comment]
average std window这个没用到，可以删去，感谢您的指出！
