### ISSUE TITLE
百度是中国公司吗？为何鄙视中文文档？

### ISSUE THREAD

**Issue by chairmanview** [baidu/Paddle#513]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [x] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [x] Did you retrieve your issue from widespread search engines ?
- [x] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [x] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by gangliao** [comment]
你好 @chairmanview

我们是一家中文公司，我们没有鄙视中文文档，这个是Issue 提问的模板，为了与Readme主页保持一致，所以我们采用了英文。

我们目前正在大力支持中文文档的完善，感谢您的关注。

**Comment by chairmanview** [comment]
谢谢回复，希望Readme主页可以像其他项目一样放置中文文档链接，以造福数量 巨大的中国程序员。非常感谢！非常支持百度人工智能项目。

**Comment by lizhaoch** [comment]
没事，英文写的能看明白就成。

**Comment by gangliao** [comment]
@chairmanview 希望这个PR 能解决你们的问题，谢谢。

**Comment by lovesif** [comment]
进来看见Readme全英文就有点失望

**Comment by gangliao** [comment]
@lovesif  对于这样的项目，我想你也会觉得readme中文并不合适，谢谢关注。

**Comment by chairmanview** [comment]
@gangliao 非常感谢采纳意见，希望中文文档能不断完善，大公司的社会责任至少应该为了培育更多的本土技术人才吧，直到所有人都觉得readme没有中文并不合适，谢谢。
