### ISSUE TITLE
运行vgg_16_cifar 错误

### ISSUE THREAD

**Issue by zhuyong0000** [baidu/Paddle#55]
运行./train.sh 出现下面错误：
/usr/local/bin/paddle: line 46:   209 Illegal instruction     ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

运行的环境是paddledev/paddle:cpu-demo-latest，paddle版本为:
PaddlePaddle 0.8.0b, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:

**Comment by qingqing01** [comment]
Note this option `with_avx: ON`, so you should make sure your CPU supports avx instructions.

**Comment by zhuyong0000** [comment]
的确是不支持avx指令，重新编译就好了
