### ISSUE TITLE
Illegal instruction on centos7.0

### ISSUE THREAD

**Issue by happyllf** [baidu/Paddle#58]
I built paddle from source code on centos7.0 successfully.
But when I try to run paddle_trainer or other binary files, it raise:
[root@iZ28zy4uk59Z bin]# ./paddle_trainer 
Illegal instruction
What is wrong?

**Comment by emailweixu** [comment]
Perhaps it's because your cpu does not support avx. Can you try with cmake -DWITH_AVX=OFF?

**Comment by happyllf** [comment]
it works, thanks very much.
