### ISSUE TITLE
paddle.trainer .config_parser 

### ISSUE THREAD

**Issue by mingtop** [baidu/Paddle#6]
I0831 15:27:18.271451 18844 Util.cpp:113] Calling runInitFunctions
I0831 15:27:18.271617 18844 Util.cpp:126] Call runInitFunctions done.
F0831 15:27:18.277050 18844 PythonUtil.cpp:120] Check failed: (pyModule) != nullptr Python Error: <type 'exceptions.ImportError'> : No module named paddle.trainer.config_parser
Python Callstack: 
Import Python Modulepaddle.trainer.config_parser failed.
*** Check failure stack trace: ***
    @     0x7f6f31c25daa  (unknown)
    @     0x7f6f31c25ce4  (unknown)
    @     0x7f6f31c256e6  (unknown)
    @     0x7f6f31c28687  (unknown)
    @           0x832e19  paddle::callPythonFuncRetPyObj()
    @           0x832ffc  paddle::callPythonFunc()
    @           0x6a94e3  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x6a9b24  paddle::TrainerConfigHelper::createFromFlags()
    @           0x53af73  main
    @     0x7f6f30e31f45  (unknown)
    @           0x5466b5  (unknown)
    @              (nil)  (unknown)
/home/jamin/Paddle/bin/paddle: line 46: 18844 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

----
I used anaconda python ,  at first I make install to /opt/Paddle. 
 I think this error is because I use the sudo make install ?  
when I use ipython , I can import paddle.trainer.config_parser well , but I can't train by ./train.sh ,
?

**Comment by emailweixu** [comment]
paddlepaddle has not been tested against anaconda python. Can you check which python paddlepaddle is linked with by looking at build/CMakeCache file?

**Comment by reyoung** [comment]
Maybe you need install PaddlePaddle's python package manually. Try to file paddle*.whl in your install directory. It normally at "/usr/local/opt/paddle/share/wheels/" if you did not change DESTDIR or CMAKE_INSTALL_PREFIX.

During make process, PaddlePaddle will install some python package to default python interpreter in system, not anaconda.

**Comment by mingtop** [comment]
@emailweixu 

I added this  to build: 

cmake -DWITH_GPU=ON -DWITH_DOC=OFF -DWITH_SWIG_PY=ON -DCMAKE_INSTALL_PREFIX=/home/youhost -DPYTHON_INCLUDE_DIR=/home/youhost/anaconda/include/python2.7 -DPYTHON_LIBRARY=/home/youhost/anaconda/lib/libpython2.7.so ..

From cmake file , I found this: 
if(WITH_PYTHON)
  find_package(PythonLibs 2.7 REQUIRED)
  find_package(PythonInterp REQUIRED)
  find_package(NumPy REQUIRED)
endif()
so to make python find my python libs I added :  -DPYTHON_LIBRARY=/home/youhost/anaconda/lib
ref: https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html

build successed but  But still has this error ...

F0831 20:01:44.284020 28877 PythonUtil.cpp:120] Check failed: (pyModule) != nullptr Python Error: <type 'exceptions.ImportError'> : No module named paddle.trainer.config_parser

太多坑了啊.

Another: gflags no found .

Hope your team slove this , Thank you every much~

**Comment by mingtop** [comment]
@reyoung  yes .  pypaddle_***.whl  and paddle_***.whl in my install path.

**Comment by mingtop** [comment]
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.

**Comment by reyoung** [comment]
@mingtop Just run anaconda's pip install these wheels, and will solve this problem

**Comment by Xiaomi2008** [comment]
I'm having the  same problem when calling train.sh

**Comment by qingqing01** [comment]
@mingtop @Xiaomi2008  I have tested against anaconda2 python, I can run train.sh successfully.  And the  python package is installed in ` /home/xxx/anaconda2/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg` on my machine which is CentOS.  

@Xiaomi2008 You may need to install PaddlePaddle's python package manually as @reyoung mentioned above.

**Comment by Xiaomi2008** [comment]
@qingqing01
 I used  pip install   pypaddle_*.whl and paddle_*.whl , the problem is still exist and I  use  python2.7, not  anaconda python. please help.

**Comment by qingqing01** [comment]
@Xiaomi2008 You should ensure that the python used for compiling and running PaddlePaddle is the same. Then if you have install paddle-xxx.wh successfully.  You maybe see the package like: `your/python/path(or system lib path)/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/`. 

You can test it as follows. If there is no problem when importing, then installation is successful and I think it will be ok when run train.sh.

```
python
import paddle.trainer.config_parser
```

**Comment by Xiaomi2008** [comment]
@qingqing01 I did see  paddle in xxx/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/ 
and I import paddle.trainer.config_parser with no error.  But still got No this error when running train.sh.
BTW, my system is Ubuntu 14.04 server

**Comment by reyoung** [comment]
@Xiaomi2008 Will the latest PaddlePaddle get this error? We did some fixes in 674d69ce57ff4d05aad20ddca2d91bc56870a183 .

**Comment by zhuyong0000** [comment]
还是有 ImportError: No module named _sysconfigdata_nd的错误
需要将paddle\utils\PythonUtil.cpp的
Py_SetProgramName(argv[0]);
改为
Py_SetProgramName((char*)"python");
就正常了
