### ISSUE TITLE
Cudnn Batch-normalization not working with cudnn-v4

### ISSUE THREAD

**Issue by zchen0211** [baidu/Paddle#60]
Hi,

I tried make-test with cudnn v4. The batch-normalization reports "segmentation fault" problem when I make test.

The Cudnn-v5 version works without problems. (Maybe cudnn-v5 suggested?)

**Comment by qingqing01** [comment]
Thanks for your feedback. We suggest to use cudnn-v5 or cudnn-v5.1. And I will fix it. Thanks!

**Comment by qingqing01** [comment]
We have fixed this problem, the code is https://github.com/baidu/Paddle/pull/71
