### ISSUE TITLE
line 46:  3085 Illegal instruction 

### ISSUE THREAD

**Issue by hdulbj** [baidu/Paddle#62]
I built paddle from source code on ubuntu14 successfully.
But when I try to run demo sentiment，./train.sh，it raise
what's wrong?

I0910 01:24:00.869675  3085 Util.cpp:113] Calling runInitFunctions
I0910 01:24:00.870432  3085 Util.cpp:126] Call runInitFunctions done.
[INFO 2016-09-10 01:24:02,138 networks.py:1122] The input order is [word, label]
[INFO 2016-09-10 01:24:02,138 networks.py:1129] The output order is [__cost_0__]
I0910 01:24:02.245304  3085 Trainer.cpp:169] trainer mode: Normal
I0910 01:24:12.127163  3085 PyDataProvider2.cpp:219] loading dataprovider dataprovider::process
[INFO 2016-09-10 01:24:12,160 dataprovider.py:22] dict len : 101745
I0910 01:24:12.680724  3085 PyDataProvider2.cpp:219] loading dataprovider dataprovider::process
[INFO 2016-09-10 01:24:12,681 dataprovider.py:22] dict len : 101745
I0910 01:24:12.687304  3085 GradientMachine.cpp:134] Initing parameters..
I0910 01:24:13.452847  3085 GradientMachine.cpp:141] Init parameters done.
Current Layer forward/backward stack is 
LayerName: __lstmemory_0__
LayerName: __fc_layer_0__
LayerName: __embedding_0__
LayerName: word
*** Aborted at 1473495865 (unix time) try "date -d @1473495865" if you are using GNU date ***
Current Layer forward/backward stack is 
PC: @           0x7b0581 hppl::relu()
Current Layer forward/backward stack is 
*** SIGILL (@0x7b0581) received by PID 3085 (TID 0x7f38e974a700) from PID 8062337; stack trace: ***
Current Layer forward/backward stack is 
    @     0x7f39014e5340 (unknown)
Current Layer forward/backward stack is 
    @           0x7b0581 hppl::relu()
Current Layer forward/backward stack is 
    @           0x5b722c paddle::LstmCompute::forwardOneSequence<>()
Current Layer forward/backward stack is 
    @           0x5b77cb paddle::LstmCompute::forwardBatch<>()
Current Layer forward/backward stack is 
    @           0x62b278 paddle::LstmLayer::forwardBatch()
Current Layer forward/backward stack is 
    @           0x62cad0 paddle::LstmLayer::forward()
Current Layer forward/backward stack is 
    @           0x53749c paddle::NeuralNetwork::forward()
Current Layer forward/backward stack is 
    @           0x54e447 paddle::TrainerThread::forward()
Current Layer forward/backward stack is 
    @           0x55027c paddle::TrainerThread::computeThread()
Current Layer forward/backward stack is 
    @     0x7f39004a1a60 (unknown)
Current Layer forward/backward stack is 
    @     0x7f39014dd182 start_thread
Current Layer forward/backward stack is 
    @     0x7f38ffc0930d (unknown)
Current Layer forward/backward stack is 
    @                0x0 (unknown)
/home/lbj/Paddle-master/build/bin/paddle: line 46:  3085 Illegal instruction     (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by comeonfox** [comment]
Check if your cpu supports avx instructions, if not, try to compile PaddlePaddle with WITH_AVX=OFF

**Comment by hdulbj** [comment]
first i did'nt turn it off,when i use "paddle train --help",it raise "illegal instruction".But when i already turned it off,"paddle train --help" cmd is ok.However, when i use the demo sentiment,cmd "./train"i raised the error.So what's wrong?

**Comment by reyoung** [comment]
@hdulbj  The fixes is already checkin in version 4a880f03c3e6881ca04c408b32921c33482f44b7. Please get the latest code and rebuild, reinstall paddle.

It will fix the sigill here.

**Comment by hdulbj** [comment]
Thx,it worked.but a new problem appears
