### ISSUE TITLE
支持mac os吗

### ISSUE THREAD

**Issue by wenjunyang** [baidu/Paddle#7]

**Comment by reyoung** [comment]
osx will support soon.  In fact, current PaddlePaddle code can compiled with clang compiler. It just needs to port some pthread API to osx (OSX lacks of thread barrier, deprecated Semaphore). The code is under review, and will commit soon when finish test.

**Comment by gangliao** [comment]
I will merge this feature soon after I fixed 2 exist bugs. You can try it from my repo: https://github.com/gangliao/Paddle

**Comment by gangliao** [comment]
@wenjunyang Mac OSX is supported now, you can build it follow this page:
http://www.paddlepaddle.org/doc/build/build_from_source.html
