### ISSUE TITLE
 ptr Fail to allocate GPU memory 7168 bytes

### ISSUE THREAD

**Issue by songdaojun** [baidu/Paddle#91]
I0919 11:01:25.650101 39674 Trainer.cpp:169] trainer mode: Normal
F0919 11:01:25.650348 39674 Allocator.h:83] Check failed: ptr Fail to allocate GPU memory 7168 bytes
*** Check failure stack trace: ***
    @     0x7f6fe604addd  google::LogMessage::Fail()
    @     0x7f6fe604cc9f  google::LogMessage::SendToLog()
    @     0x7f6fe604a973  google::LogMessage::Flush()
    @     0x7f6fe604d5be  google::LogMessageFatal::~LogMessageFatal()
    @           0x73178e  paddle::GpuAllocator::alloc()
    @           0x726e96  paddle::PoolAllocator::alloc()
    @           0x7266ef  paddle::GpuMemoryHandle::GpuMemoryHandle()
    @           0x735fee  paddle::GpuVectorT<>::GpuVectorT()
    @           0x739e58  paddle::VectorT<>::create()
    @           0x73b479  paddle::VectorT<>::createParallelVector()
    @           0x5e9276  paddle::Parameter::enableType()
    @           0x5e5d2c  paddle::parameterInitNN()
    @           0x5e7f51  paddle::NeuralNetwork::init()
    @           0x5f6bf8  paddle::GradientMachine::create()
    @           0x661975  paddle::TrainerInternal::init()
    @           0x65da47  paddle::Trainer::init()
    @           0x50b115  main

**Comment by hedaoyuan** [comment]
Paddle can compile with only CPU(if WITH_GPU=off).  Check paddle version with --version command.
If cpu version, you can't use use_gpu=1 in command line parameters.

**Comment by songdaojun** [comment]
But, It's a powerful computer,  with gpu enabled.

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
Stepping:              1
CPU MHz:               2499.902
BogoMIPS:              4994.15
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0-63

**Comment by songdaojun** [comment]
lspci | grep -i nvidia
03:00.0 3D controller: NVIDIA Corporation Device 17fd (rev a1)
83:00.0 3D controller: NVIDIA Corporation Device 17fd (rev a1)

**Comment by hedaoyuan** [comment]
Close issue. If there are problems, reopen this issue.
