### ISSUE TITLE
Install whl failed

### ISSUE THREAD

**Issue by apollos** [baidu/Paddle#94]
I can successfully build out the paddle but while I install "py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl", it failed and promt:
~/workspace/Paddle/build$ sudo pip install /opt/paddle/share/wheels/*.whl
py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/yu/.pip/pip.log

How shall I fix it or work around it?

My configuration:
cmake -DWITH_GPU=ON -DWITH_DOC=OFF -DMKL_ROOT=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/ -DCUDNN_ROOT=/usr/local/cuda -DWITH_SWIG_PY=ON -DCMAKE_INSTALL_PREFIX=/ ..

paddle version
PaddlePaddle 0.8.0b0, compiled with
    with_avx: ON
    with_gpu: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:

**Comment by F0REacH** [comment]
Hi, @apollos . I've had similar issue: python/pip was installed with multiple versions 2.7 and 3.
```
foreach@linux-PC:~> pip2.7 --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
foreach@linux-PC:~> pip --version
pip 8.1.1 from /usr/lib/python3.5/site-packages (python 3.5)
```
Had to run 
> foreach@linux-PC:~> sudo update-alternatives --config pip 
to set pip version to 2.7 manually

**Comment by apollos** [comment]
Thanks for your help. But it seems not my issue

:~$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

My pip is from python2.7.

And I do try pip2 but same issue

sudo pip2 install py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl 
py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/yu/.pip/pip.log

 1 ------------------------------------------------------------
  2 /usr/bin/pip2 run on Tue Sep 20 18:54:32 2016
  3 py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
  4 Exception information:
  5 Traceback (most recent call last):
  6   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
  7     status = self.run(options, args)
  8   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
  9     InstallRequirement.from_line(name, None))
 10   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
 11     raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
 12 UnsupportedWheel: py_paddle-0.8.0b0-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by reyoung** [comment]
This because the pip version is too old, but wheel package is latest.

Please update your pip by `pip install pip --upgrade`

**Comment by apollos** [comment]
Thanks a lot.
