### ISSUE TITLE
How to label the input sequence after I have trained a CTC network in Paddle?

### ISSUE THREAD

**Issue by ganji15** [baidu/Paddle#97]
I want to  label the input sequence after I have trained a CTC network, but I have no idea to label the sequences. Acrodding to the related papers, the task is simliar with path decoding. There are 2 method to decode: "best path decoding" and "prefix search decoding" . So, how can I find most probable labelling with "best path decoding" and "prefix search decoding" in Paddle, or I have to do this labeling by meself? 

Can anyone provide any suggestions or examples?  Thank you?

==============================
ctc network
---------------------------------------------------
```python
# Should the output of tmp be a sequnce of  probability vector such as [[f,...], [f,....]]?
tmp = fc_layer(input=x1,
              size=num_classes + 1,
              act=SoftmaxActivation())

ctc = ctc_layer(input=tmp,
                 label=y,
                 size=num_classes + 1)
ctc_eval = ctc_error_evaluator(input=ctc, label=y)

**Comment by qingqing01** [comment]
You can output the probability of softmax activation and predict the top-1 label for each time step.
Then you can shrink the labels according the CTC rule using a Python script by yourself.

1. output probability setting outputs as follows:
```
outputs(tmp)
```
Then, add command line argument in `paddle train --job=test ...`  as follows. Then probability file will be saved in output_path/rank-00000.
```
--predict_output_dir=output_path
```

2. the simple shrinking rule:
   * predict the top-1 label for each time step.
   * remove `blank` char, namely, the label `num_classes ` (since the label is 0, 1, 2, ..., num_classes).
   * shrink the *continuous repeating* character into one character.
 For example:  `_aa_b____c_ddd__ `  ->   `abcd`

**Comment by ganji15** [comment]
@qingqing01 
"The output of tmp is a sequnce of  probability vector such as [[f,...], [f,....]], and every probability vector is label probability of that corresponding time_step. " Is that correct? 

 So, if I want to label with the  "best path decoding" method, I can get the label at time_step t by maximizing the label probability vector[f...] at time_step t, then I should combine all obtained labels of all time_steps into a sequence  like "_aa_b____c_ddd__" , finally  I should shrink the sequence to " abcd".
Is that procedure right?

**Comment by qingqing01** [comment]
@ganji15 
Yes, you are right.  But note,  "The output of tmp is a sequnce of probability vector such as [[f,...], [f,....]]", if you use `outputs(tmp)` and `--predict_output_dir`,  each line in the file of output_path/rank-00000 is probability vector for one time step.

You also can use Python API to predict, the document is [here](http://www.paddlepaddle.org/doc/ui/predict/swig_py_paddle_en.html).

**Comment by ganji15** [comment]
@qingqing01 
Thank you!

So, I have to decode the output sequences by myself. 

Another question:
I found a function named "beam_search" in paddle,  and the document says that "Beam search is a heuristic search algorithm used in sequence generation."  
Can this function or any similar functions in Paddle help me to label the sequence with "prefix search decoding" method?

**Comment by emailweixu** [comment]
you can also use maxid_layer() to get the most probable label sequence

**Comment by ganji15** [comment]
@emailweixu  Thank you, I think you are right!
